// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeggieSwapServer.Data;

namespace VeggieSwapServer.Data.Migrations
{
    [DbContext(typeof(VeggieSwapServerContext))]
    [Migration("20210518135539_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 889, DateTimeKind.Local).AddTicks(2991),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 889, DateTimeKind.Local).AddTicks(2991),
                            PostalCode = 9000,
                            StreetName = "Anti-Veggiestraat",
                            StreetNumber = 89,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 889, DateTimeKind.Local).AddTicks(5190),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 889, DateTimeKind.Local).AddTicks(5190),
                            PostalCode = 9000,
                            StreetName = "Pieterstreaat",
                            StreetNumber = 45,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 889, DateTimeKind.Local).AddTicks(5233),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 889, DateTimeKind.Local).AddTicks(5233),
                            PostalCode = 9000,
                            StreetName = "Nickstraat",
                            StreetNumber = 74,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 889, DateTimeKind.Local).AddTicks(5236),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 889, DateTimeKind.Local).AddTicks(5236),
                            PostalCode = 1000,
                            StreetName = "Driesstraat",
                            StreetNumber = 66,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 889, DateTimeKind.Local).AddTicks(5239),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 889, DateTimeKind.Local).AddTicks(5239),
                            PostalCode = 2000,
                            StreetName = "Kobestraat",
                            StreetNumber = 85,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 889, DateTimeKind.Local).AddTicks(5242),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 889, DateTimeKind.Local).AddTicks(5242),
                            PostalCode = 1000,
                            StreetName = "Lookbroodjesstraat",
                            StreetNumber = 43,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 889, DateTimeKind.Local).AddTicks(5245),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 889, DateTimeKind.Local).AddTicks(5245),
                            PostalCode = 9050,
                            StreetName = "Greenpeacestraat",
                            StreetNumber = 1,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 889, DateTimeKind.Local).AddTicks(5248),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 889, DateTimeKind.Local).AddTicks(5248),
                            PostalCode = 1000,
                            StreetName = "Kotsvisstraat",
                            StreetNumber = 96,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 889, DateTimeKind.Local).AddTicks(5251),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 889, DateTimeKind.Local).AddTicks(5251),
                            PostalCode = 2000,
                            StreetName = "Greenlivesmattertoostraat",
                            StreetNumber = 420,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 889, DateTimeKind.Local).AddTicks(5254),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 889, DateTimeKind.Local).AddTicks(5254),
                            PostalCode = 9070,
                            StreetName = "Geenpolitiekinhetprojectstraat",
                            StreetNumber = 200,
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 889, DateTimeKind.Local).AddTicks(5258),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 889, DateTimeKind.Local).AddTicks(5258),
                            PostalCode = 9500,
                            StreetName = "Kalfslapjesstraat",
                            StreetNumber = 32,
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 889, DateTimeKind.Local).AddTicks(5261),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 889, DateTimeKind.Local).AddTicks(5261),
                            PostalCode = 1000,
                            StreetName = "Blacklivesmatterstraat",
                            StreetNumber = 78,
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 889, DateTimeKind.Local).AddTicks(5264),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 889, DateTimeKind.Local).AddTicks(5264),
                            PostalCode = 9020,
                            StreetName = "Worstenbroodjesstraat",
                            StreetNumber = 4,
                            UserId = 13
                        });
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EuroAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("VAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("Purchases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 894, DateTimeKind.Local).AddTicks(6432),
                            EuroAmount = 6.9m,
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 894, DateTimeKind.Local).AddTicks(6432),
                            VAmount = 69m,
                            WalletId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 894, DateTimeKind.Local).AddTicks(8285),
                            EuroAmount = 2m,
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 894, DateTimeKind.Local).AddTicks(8285),
                            VAmount = 20m,
                            WalletId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 894, DateTimeKind.Local).AddTicks(8303),
                            EuroAmount = 42m,
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 894, DateTimeKind.Local).AddTicks(8303),
                            VAmount = 420m,
                            WalletId = 5
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 894, DateTimeKind.Local).AddTicks(8306),
                            EuroAmount = 10m,
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 894, DateTimeKind.Local).AddTicks(8306),
                            VAmount = 100m,
                            WalletId = 6
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 894, DateTimeKind.Local).AddTicks(8310),
                            EuroAmount = 3.6m,
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 894, DateTimeKind.Local).AddTicks(8310),
                            VAmount = 36m,
                            WalletId = 12
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 894, DateTimeKind.Local).AddTicks(8313),
                            EuroAmount = 7.8m,
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 894, DateTimeKind.Local).AddTicks(8313),
                            VAmount = 78m,
                            WalletId = 10
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 894, DateTimeKind.Local).AddTicks(8316),
                            EuroAmount = 9.8m,
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 894, DateTimeKind.Local).AddTicks(8316),
                            VAmount = 98m,
                            WalletId = 9
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 894, DateTimeKind.Local).AddTicks(8319),
                            EuroAmount = 5m,
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 894, DateTimeKind.Local).AddTicks(8319),
                            VAmount = 50m,
                            WalletId = 7
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 894, DateTimeKind.Local).AddTicks(8323),
                            EuroAmount = 13m,
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 894, DateTimeKind.Local).AddTicks(8323),
                            VAmount = 130m,
                            WalletId = 3
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 894, DateTimeKind.Local).AddTicks(8326),
                            EuroAmount = 2m,
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 894, DateTimeKind.Local).AddTicks(8326),
                            VAmount = 20m,
                            WalletId = 4
                        });
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 891, DateTimeKind.Local).AddTicks(8776),
                            ImageUrl = "apples.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 891, DateTimeKind.Local).AddTicks(8776),
                            Name = "apples"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 891, DateTimeKind.Local).AddTicks(9992),
                            ImageUrl = "artichokes.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 891, DateTimeKind.Local).AddTicks(9992),
                            Name = "artichokes"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(11),
                            ImageUrl = "asparaguses.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(11),
                            Name = "asparaguses"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(15),
                            ImageUrl = "bananas.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(15),
                            Name = "bananas"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(17),
                            ImageUrl = "bell-peppers.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(17),
                            Name = "bell-peppers"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(20),
                            ImageUrl = "blueberries.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(20),
                            Name = "blueberries"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(24),
                            ImageUrl = "bok-choy.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(24),
                            Name = "bok-choy"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(27),
                            ImageUrl = "broccoli.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(27),
                            Name = "broccoli"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(30),
                            ImageUrl = "brussels-sprouts.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(30),
                            Name = "brussels-sprouts"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(33),
                            ImageUrl = "carrots.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(33),
                            Name = "carrots"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(36),
                            ImageUrl = "cherries.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(36),
                            Name = "cherries"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(39),
                            ImageUrl = "chilis.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(39),
                            Name = "chilis"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(42),
                            ImageUrl = "coconuts.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(42),
                            Name = "coconuts"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(44),
                            ImageUrl = "coriander.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(44),
                            Name = "coriander"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(47),
                            ImageUrl = "corn.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(47),
                            Name = "corn"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(50),
                            ImageUrl = "cucumbers.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(50),
                            Name = "cucumbers"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(53),
                            ImageUrl = "dragon-fruits.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(53),
                            Name = "dragon-fruits"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(55),
                            ImageUrl = "durians.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(55),
                            Name = "durians"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(58),
                            ImageUrl = "eggplants.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(58),
                            Name = "eggplants"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(61),
                            ImageUrl = "garlic.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(61),
                            Name = "garlic"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(64),
                            ImageUrl = "grapes.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(64),
                            Name = "grapes"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(67),
                            ImageUrl = "guavas.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(67),
                            Name = "guavas"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(70),
                            ImageUrl = "kiwis.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(70),
                            Name = "kiwis"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(73),
                            ImageUrl = "lemons.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(73),
                            Name = "lemons"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(75),
                            ImageUrl = "mangos.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(75),
                            Name = "mangos"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(78),
                            ImageUrl = "mangosteens.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(78),
                            Name = "mangosteens"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(81),
                            ImageUrl = "melons.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(81),
                            Name = "melons"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(84),
                            ImageUrl = "mushrooms.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(84),
                            Name = "mushrooms"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(87),
                            ImageUrl = "olives.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(87),
                            Name = "olives"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(89),
                            ImageUrl = "oranges.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(89),
                            Name = "oranges"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(92),
                            ImageUrl = "papayas.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(92),
                            Name = "papayas"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(95),
                            ImageUrl = "peaches.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(95),
                            Name = "peaches"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(98),
                            ImageUrl = "pears.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(98),
                            Name = "pears"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(100),
                            ImageUrl = "peas.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(100),
                            Name = "peas"
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(103),
                            ImageUrl = "pineapples.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(103),
                            Name = "pineapples"
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(106),
                            ImageUrl = "pomegranates.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(106),
                            Name = "pomegranates"
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(109),
                            ImageUrl = "potatoes.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(109),
                            Name = "potatoes"
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(111),
                            ImageUrl = "pumpkins.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(111),
                            Name = "pumpkins"
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(114),
                            ImageUrl = "radish.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(114),
                            Name = "radish"
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(118),
                            ImageUrl = "radishes.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(118),
                            Name = "radishes"
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(120),
                            ImageUrl = "raspberries.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(120),
                            Name = "raspberries"
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(123),
                            ImageUrl = "salad.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(123),
                            Name = "salad"
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(126),
                            ImageUrl = "salads.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(126),
                            Name = "salads"
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(128),
                            ImageUrl = "scallions.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(128),
                            Name = "scallions"
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(131),
                            ImageUrl = "spinach.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(131),
                            Name = "spinach"
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(134),
                            ImageUrl = "star-fruits.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(134),
                            Name = "star-fruits"
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(137),
                            ImageUrl = "strawberries.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(137),
                            Name = "strawberries"
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(140),
                            ImageUrl = "sweet-potatoes.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(140),
                            Name = "sweet-potatoes"
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(143),
                            ImageUrl = "tomatoes.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(143),
                            Name = "tomatoes"
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(146),
                            ImageUrl = "watermelons.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(146),
                            Name = "watermelons"
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(149),
                            ImageUrl = "v-coin.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(149),
                            Name = "v-coin"
                        });
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Trades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6377),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6377)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6409),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6409)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6413),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6413)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6415),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6415)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6418),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6418)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6421),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6421)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6424),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6424)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6427),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6427)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6429),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6429)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6432),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6432)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6435),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6435)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6437),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6437)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6441),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6441)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6443),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6443)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6446),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6446)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6449),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6449)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6451),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6451)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6454),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6454)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6457),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 892, DateTimeKind.Local).AddTicks(6457)
                        });
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.TradeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<int>("TradeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("TradeId");

                    b.HasIndex("UserId");

                    b.ToTable("TradeItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 2,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(6478),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(6478),
                            ResourceId = 51,
                            TradeId = 1,
                            UserId = 10
                        },
                        new
                        {
                            Id = 2,
                            Amount = 10,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8580),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8580),
                            ResourceId = 11,
                            TradeId = 2,
                            UserId = 8
                        },
                        new
                        {
                            Id = 3,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8652),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8652),
                            ResourceId = 32,
                            TradeId = 3,
                            UserId = 13
                        },
                        new
                        {
                            Id = 4,
                            Amount = 69,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8656),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8656),
                            ResourceId = 24,
                            TradeId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Amount = 45,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8660),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8660),
                            ResourceId = 45,
                            TradeId = 5,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            Amount = 30,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8662),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8662),
                            ResourceId = 6,
                            TradeId = 6,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            Amount = 42,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8665),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8665),
                            ResourceId = 17,
                            TradeId = 7,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            Amount = 75,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8668),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8668),
                            ResourceId = 8,
                            TradeId = 8,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            Amount = 201,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8671),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8671),
                            ResourceId = 9,
                            TradeId = 9,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            Amount = 634,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8674),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8674),
                            ResourceId = 10,
                            TradeId = 10,
                            UserId = 9
                        },
                        new
                        {
                            Id = 11,
                            Amount = 20,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8677),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8677),
                            ResourceId = 17,
                            TradeId = 11,
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            Amount = 75,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8680),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8680),
                            ResourceId = 26,
                            TradeId = 12,
                            UserId = 13
                        },
                        new
                        {
                            Id = 13,
                            Amount = 69,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8682),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8682),
                            ResourceId = 19,
                            TradeId = 1,
                            UserId = 10
                        },
                        new
                        {
                            Id = 14,
                            Amount = 25,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8685),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8685),
                            ResourceId = 49,
                            TradeId = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 15,
                            Amount = 35,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8688),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8688),
                            ResourceId = 50,
                            TradeId = 1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 16,
                            Amount = 75,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8691),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8691),
                            ResourceId = 7,
                            TradeId = 8,
                            UserId = 5
                        },
                        new
                        {
                            Id = 17,
                            Amount = 10,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8694),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8694),
                            ResourceId = 1,
                            TradeId = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 18,
                            Amount = 9,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8697),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8697),
                            ResourceId = 6,
                            TradeId = 9,
                            UserId = 1
                        },
                        new
                        {
                            Id = 19,
                            Amount = 17,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8699),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8699),
                            ResourceId = 7,
                            TradeId = 5,
                            UserId = 12
                        },
                        new
                        {
                            Id = 20,
                            Amount = 30,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8702),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8702),
                            ResourceId = 36,
                            TradeId = 1,
                            UserId = 7
                        },
                        new
                        {
                            Id = 21,
                            Amount = 78,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8705),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8705),
                            ResourceId = 23,
                            TradeId = 7,
                            UserId = 6
                        },
                        new
                        {
                            Id = 22,
                            Amount = 69,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8708),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8708),
                            ResourceId = 27,
                            TradeId = 9,
                            UserId = 9
                        },
                        new
                        {
                            Id = 23,
                            Amount = 180,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8711),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8711),
                            ResourceId = 37,
                            TradeId = 13,
                            UserId = 1
                        },
                        new
                        {
                            Id = 24,
                            Amount = 47,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8714),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8714),
                            ResourceId = 47,
                            TradeId = 7,
                            UserId = 2
                        },
                        new
                        {
                            Id = 25,
                            Amount = 20,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8717),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8717),
                            ResourceId = 48,
                            TradeId = 18,
                            UserId = 6
                        },
                        new
                        {
                            Id = 26,
                            Amount = 10,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8720),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 893, DateTimeKind.Local).AddTicks(8720),
                            ResourceId = 39,
                            TradeId = 13,
                            UserId = 7
                        });
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 882, DateTimeKind.Local).AddTicks(8282),
                            Email = "Pieter@mail.com",
                            FirstName = "Pieter",
                            ImageUrl = "https://robohash.org/Pieter",
                            IsAdmin = true,
                            LastName = "Corp",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 882, DateTimeKind.Local).AddTicks(8282),
                            PasswordHash = new byte[] { 77, 194, 166, 27, 170, 163, 13, 247, 238, 164, 255, 84, 45, 232, 135, 161, 157, 60, 69, 218, 37, 57, 183, 198, 251, 143, 71, 29, 158, 108, 22, 203, 166, 243, 53, 63, 177, 208, 251, 182, 41, 227, 6, 149, 114, 198, 169, 177, 203, 69, 134, 86, 232, 165, 20, 160, 230, 43, 133, 33, 202, 34, 90, 39 },
                            PasswordSalt = new byte[] { 28, 156, 34, 199, 227, 145, 199, 132, 30, 11, 9, 108, 114, 156, 122, 219, 95, 130, 112, 84, 29, 192, 73, 152, 0, 17, 151, 33, 12, 198, 90, 13, 15, 141, 99, 210, 14, 184, 100, 27, 63, 7, 216, 249, 28, 153, 83, 171, 211, 97, 206, 132, 47, 114, 51, 176, 1, 1, 24, 239, 178, 2, 89, 213, 163, 247, 234, 7, 87, 135, 77, 188, 133, 221, 255, 239, 213, 105, 131, 134, 208, 238, 55, 235, 197, 206, 226, 243, 25, 69, 93, 99, 108, 100, 143, 197, 233, 175, 158, 82, 135, 136, 20, 90, 184, 133, 131, 188, 201, 45, 78, 96, 25, 100, 221, 197, 57, 247, 148, 88, 143, 128, 81, 84, 102, 6, 216, 165 }
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 886, DateTimeKind.Local).AddTicks(7464),
                            Email = "Nick@mail.com",
                            FirstName = "Nick",
                            ImageUrl = "https://robohash.org/Nick",
                            IsAdmin = true,
                            LastName = "Vr",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 886, DateTimeKind.Local).AddTicks(7464),
                            PasswordHash = new byte[] { 77, 194, 166, 27, 170, 163, 13, 247, 238, 164, 255, 84, 45, 232, 135, 161, 157, 60, 69, 218, 37, 57, 183, 198, 251, 143, 71, 29, 158, 108, 22, 203, 166, 243, 53, 63, 177, 208, 251, 182, 41, 227, 6, 149, 114, 198, 169, 177, 203, 69, 134, 86, 232, 165, 20, 160, 230, 43, 133, 33, 202, 34, 90, 39 },
                            PasswordSalt = new byte[] { 28, 156, 34, 199, 227, 145, 199, 132, 30, 11, 9, 108, 114, 156, 122, 219, 95, 130, 112, 84, 29, 192, 73, 152, 0, 17, 151, 33, 12, 198, 90, 13, 15, 141, 99, 210, 14, 184, 100, 27, 63, 7, 216, 249, 28, 153, 83, 171, 211, 97, 206, 132, 47, 114, 51, 176, 1, 1, 24, 239, 178, 2, 89, 213, 163, 247, 234, 7, 87, 135, 77, 188, 133, 221, 255, 239, 213, 105, 131, 134, 208, 238, 55, 235, 197, 206, 226, 243, 25, 69, 93, 99, 108, 100, 143, 197, 233, 175, 158, 82, 135, 136, 20, 90, 184, 133, 131, 188, 201, 45, 78, 96, 25, 100, 221, 197, 57, 247, 148, 88, 143, 128, 81, 84, 102, 6, 216, 165 }
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 886, DateTimeKind.Local).AddTicks(7962),
                            Email = "Kobe@mail.com",
                            FirstName = "Kobe",
                            ImageUrl = "https://robohash.org/Kobe",
                            IsAdmin = true,
                            LastName = "Delo",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 886, DateTimeKind.Local).AddTicks(7962),
                            PasswordHash = new byte[] { 77, 194, 166, 27, 170, 163, 13, 247, 238, 164, 255, 84, 45, 232, 135, 161, 157, 60, 69, 218, 37, 57, 183, 198, 251, 143, 71, 29, 158, 108, 22, 203, 166, 243, 53, 63, 177, 208, 251, 182, 41, 227, 6, 149, 114, 198, 169, 177, 203, 69, 134, 86, 232, 165, 20, 160, 230, 43, 133, 33, 202, 34, 90, 39 },
                            PasswordSalt = new byte[] { 28, 156, 34, 199, 227, 145, 199, 132, 30, 11, 9, 108, 114, 156, 122, 219, 95, 130, 112, 84, 29, 192, 73, 152, 0, 17, 151, 33, 12, 198, 90, 13, 15, 141, 99, 210, 14, 184, 100, 27, 63, 7, 216, 249, 28, 153, 83, 171, 211, 97, 206, 132, 47, 114, 51, 176, 1, 1, 24, 239, 178, 2, 89, 213, 163, 247, 234, 7, 87, 135, 77, 188, 133, 221, 255, 239, 213, 105, 131, 134, 208, 238, 55, 235, 197, 206, 226, 243, 25, 69, 93, 99, 108, 100, 143, 197, 233, 175, 158, 82, 135, 136, 20, 90, 184, 133, 131, 188, 201, 45, 78, 96, 25, 100, 221, 197, 57, 247, 148, 88, 143, 128, 81, 84, 102, 6, 216, 165 }
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 886, DateTimeKind.Local).AddTicks(7995),
                            Email = "Dries@mail.com",
                            FirstName = "Dries",
                            ImageUrl = "https://robohash.org/Dries",
                            IsAdmin = true,
                            LastName = "Maes",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 886, DateTimeKind.Local).AddTicks(7995),
                            PasswordHash = new byte[] { 77, 194, 166, 27, 170, 163, 13, 247, 238, 164, 255, 84, 45, 232, 135, 161, 157, 60, 69, 218, 37, 57, 183, 198, 251, 143, 71, 29, 158, 108, 22, 203, 166, 243, 53, 63, 177, 208, 251, 182, 41, 227, 6, 149, 114, 198, 169, 177, 203, 69, 134, 86, 232, 165, 20, 160, 230, 43, 133, 33, 202, 34, 90, 39 },
                            PasswordSalt = new byte[] { 28, 156, 34, 199, 227, 145, 199, 132, 30, 11, 9, 108, 114, 156, 122, 219, 95, 130, 112, 84, 29, 192, 73, 152, 0, 17, 151, 33, 12, 198, 90, 13, 15, 141, 99, 210, 14, 184, 100, 27, 63, 7, 216, 249, 28, 153, 83, 171, 211, 97, 206, 132, 47, 114, 51, 176, 1, 1, 24, 239, 178, 2, 89, 213, 163, 247, 234, 7, 87, 135, 77, 188, 133, 221, 255, 239, 213, 105, 131, 134, 208, 238, 55, 235, 197, 206, 226, 243, 25, 69, 93, 99, 108, 100, 143, 197, 233, 175, 158, 82, 135, 136, 20, 90, 184, 133, 131, 188, 201, 45, 78, 96, 25, 100, 221, 197, 57, 247, 148, 88, 143, 128, 81, 84, 102, 6, 216, 165 }
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 886, DateTimeKind.Local).AddTicks(8018),
                            Email = "BartjeWevertje@mail.com",
                            FirstName = "BartjeWevertje",
                            ImageUrl = "https://robohash.org/BartjeWevertje",
                            IsAdmin = false,
                            LastName = "Wevertje",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 886, DateTimeKind.Local).AddTicks(8018),
                            PasswordHash = new byte[] { 77, 194, 166, 27, 170, 163, 13, 247, 238, 164, 255, 84, 45, 232, 135, 161, 157, 60, 69, 218, 37, 57, 183, 198, 251, 143, 71, 29, 158, 108, 22, 203, 166, 243, 53, 63, 177, 208, 251, 182, 41, 227, 6, 149, 114, 198, 169, 177, 203, 69, 134, 86, 232, 165, 20, 160, 230, 43, 133, 33, 202, 34, 90, 39 },
                            PasswordSalt = new byte[] { 28, 156, 34, 199, 227, 145, 199, 132, 30, 11, 9, 108, 114, 156, 122, 219, 95, 130, 112, 84, 29, 192, 73, 152, 0, 17, 151, 33, 12, 198, 90, 13, 15, 141, 99, 210, 14, 184, 100, 27, 63, 7, 216, 249, 28, 153, 83, 171, 211, 97, 206, 132, 47, 114, 51, 176, 1, 1, 24, 239, 178, 2, 89, 213, 163, 247, 234, 7, 87, 135, 77, 188, 133, 221, 255, 239, 213, 105, 131, 134, 208, 238, 55, 235, 197, 206, 226, 243, 25, 69, 93, 99, 108, 100, 143, 197, 233, 175, 158, 82, 135, 136, 20, 90, 184, 133, 131, 188, 201, 45, 78, 96, 25, 100, 221, 197, 57, 247, 148, 88, 143, 128, 81, 84, 102, 6, 216, 165 }
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 886, DateTimeKind.Local).AddTicks(8039),
                            Email = "Stofzuiger@mail.com",
                            FirstName = "Stofzuiger",
                            ImageUrl = "https://robohash.org/Stofzuiger",
                            IsAdmin = false,
                            LastName = "Zuiger",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 886, DateTimeKind.Local).AddTicks(8039),
                            PasswordHash = new byte[] { 77, 194, 166, 27, 170, 163, 13, 247, 238, 164, 255, 84, 45, 232, 135, 161, 157, 60, 69, 218, 37, 57, 183, 198, 251, 143, 71, 29, 158, 108, 22, 203, 166, 243, 53, 63, 177, 208, 251, 182, 41, 227, 6, 149, 114, 198, 169, 177, 203, 69, 134, 86, 232, 165, 20, 160, 230, 43, 133, 33, 202, 34, 90, 39 },
                            PasswordSalt = new byte[] { 28, 156, 34, 199, 227, 145, 199, 132, 30, 11, 9, 108, 114, 156, 122, 219, 95, 130, 112, 84, 29, 192, 73, 152, 0, 17, 151, 33, 12, 198, 90, 13, 15, 141, 99, 210, 14, 184, 100, 27, 63, 7, 216, 249, 28, 153, 83, 171, 211, 97, 206, 132, 47, 114, 51, 176, 1, 1, 24, 239, 178, 2, 89, 213, 163, 247, 234, 7, 87, 135, 77, 188, 133, 221, 255, 239, 213, 105, 131, 134, 208, 238, 55, 235, 197, 206, 226, 243, 25, 69, 93, 99, 108, 100, 143, 197, 233, 175, 158, 82, 135, 136, 20, 90, 184, 133, 131, 188, 201, 45, 78, 96, 25, 100, 221, 197, 57, 247, 148, 88, 143, 128, 81, 84, 102, 6, 216, 165 }
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 886, DateTimeKind.Local).AddTicks(8059),
                            Email = "Dirk@mail.com",
                            FirstName = "Dirk",
                            ImageUrl = "https://robohash.org/Dirk",
                            IsAdmin = false,
                            LastName = "Visser",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 886, DateTimeKind.Local).AddTicks(8059),
                            PasswordHash = new byte[] { 77, 194, 166, 27, 170, 163, 13, 247, 238, 164, 255, 84, 45, 232, 135, 161, 157, 60, 69, 218, 37, 57, 183, 198, 251, 143, 71, 29, 158, 108, 22, 203, 166, 243, 53, 63, 177, 208, 251, 182, 41, 227, 6, 149, 114, 198, 169, 177, 203, 69, 134, 86, 232, 165, 20, 160, 230, 43, 133, 33, 202, 34, 90, 39 },
                            PasswordSalt = new byte[] { 28, 156, 34, 199, 227, 145, 199, 132, 30, 11, 9, 108, 114, 156, 122, 219, 95, 130, 112, 84, 29, 192, 73, 152, 0, 17, 151, 33, 12, 198, 90, 13, 15, 141, 99, 210, 14, 184, 100, 27, 63, 7, 216, 249, 28, 153, 83, 171, 211, 97, 206, 132, 47, 114, 51, 176, 1, 1, 24, 239, 178, 2, 89, 213, 163, 247, 234, 7, 87, 135, 77, 188, 133, 221, 255, 239, 213, 105, 131, 134, 208, 238, 55, 235, 197, 206, 226, 243, 25, 69, 93, 99, 108, 100, 143, 197, 233, 175, 158, 82, 135, 136, 20, 90, 184, 133, 131, 188, 201, 45, 78, 96, 25, 100, 221, 197, 57, 247, 148, 88, 143, 128, 81, 84, 102, 6, 216, 165 }
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 886, DateTimeKind.Local).AddTicks(8078),
                            Email = "Andreas@mail.com",
                            FirstName = "Andreas",
                            ImageUrl = "https://robohash.org/Andreas",
                            IsAdmin = false,
                            LastName = "VanGrieken",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 886, DateTimeKind.Local).AddTicks(8078),
                            PasswordHash = new byte[] { 77, 194, 166, 27, 170, 163, 13, 247, 238, 164, 255, 84, 45, 232, 135, 161, 157, 60, 69, 218, 37, 57, 183, 198, 251, 143, 71, 29, 158, 108, 22, 203, 166, 243, 53, 63, 177, 208, 251, 182, 41, 227, 6, 149, 114, 198, 169, 177, 203, 69, 134, 86, 232, 165, 20, 160, 230, 43, 133, 33, 202, 34, 90, 39 },
                            PasswordSalt = new byte[] { 28, 156, 34, 199, 227, 145, 199, 132, 30, 11, 9, 108, 114, 156, 122, 219, 95, 130, 112, 84, 29, 192, 73, 152, 0, 17, 151, 33, 12, 198, 90, 13, 15, 141, 99, 210, 14, 184, 100, 27, 63, 7, 216, 249, 28, 153, 83, 171, 211, 97, 206, 132, 47, 114, 51, 176, 1, 1, 24, 239, 178, 2, 89, 213, 163, 247, 234, 7, 87, 135, 77, 188, 133, 221, 255, 239, 213, 105, 131, 134, 208, 238, 55, 235, 197, 206, 226, 243, 25, 69, 93, 99, 108, 100, 143, 197, 233, 175, 158, 82, 135, 136, 20, 90, 184, 133, 131, 188, 201, 45, 78, 96, 25, 100, 221, 197, 57, 247, 148, 88, 143, 128, 81, 84, 102, 6, 216, 165 }
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 886, DateTimeKind.Local).AddTicks(8099),
                            Email = "Mihiel@mail.com",
                            FirstName = "Mihiel",
                            ImageUrl = "https://robohash.org/Mihiel",
                            IsAdmin = false,
                            LastName = "Mihoen",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 886, DateTimeKind.Local).AddTicks(8099),
                            PasswordHash = new byte[] { 77, 194, 166, 27, 170, 163, 13, 247, 238, 164, 255, 84, 45, 232, 135, 161, 157, 60, 69, 218, 37, 57, 183, 198, 251, 143, 71, 29, 158, 108, 22, 203, 166, 243, 53, 63, 177, 208, 251, 182, 41, 227, 6, 149, 114, 198, 169, 177, 203, 69, 134, 86, 232, 165, 20, 160, 230, 43, 133, 33, 202, 34, 90, 39 },
                            PasswordSalt = new byte[] { 28, 156, 34, 199, 227, 145, 199, 132, 30, 11, 9, 108, 114, 156, 122, 219, 95, 130, 112, 84, 29, 192, 73, 152, 0, 17, 151, 33, 12, 198, 90, 13, 15, 141, 99, 210, 14, 184, 100, 27, 63, 7, 216, 249, 28, 153, 83, 171, 211, 97, 206, 132, 47, 114, 51, 176, 1, 1, 24, 239, 178, 2, 89, 213, 163, 247, 234, 7, 87, 135, 77, 188, 133, 221, 255, 239, 213, 105, 131, 134, 208, 238, 55, 235, 197, 206, 226, 243, 25, 69, 93, 99, 108, 100, 143, 197, 233, 175, 158, 82, 135, 136, 20, 90, 184, 133, 131, 188, 201, 45, 78, 96, 25, 100, 221, 197, 57, 247, 148, 88, 143, 128, 81, 84, 102, 6, 216, 165 }
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 886, DateTimeKind.Local).AddTicks(8119),
                            Email = "Luc@mail.com",
                            FirstName = "Luc",
                            ImageUrl = "https://robohash.org/Luc",
                            IsAdmin = false,
                            LastName = "DeHaantje",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 886, DateTimeKind.Local).AddTicks(8119),
                            PasswordHash = new byte[] { 77, 194, 166, 27, 170, 163, 13, 247, 238, 164, 255, 84, 45, 232, 135, 161, 157, 60, 69, 218, 37, 57, 183, 198, 251, 143, 71, 29, 158, 108, 22, 203, 166, 243, 53, 63, 177, 208, 251, 182, 41, 227, 6, 149, 114, 198, 169, 177, 203, 69, 134, 86, 232, 165, 20, 160, 230, 43, 133, 33, 202, 34, 90, 39 },
                            PasswordSalt = new byte[] { 28, 156, 34, 199, 227, 145, 199, 132, 30, 11, 9, 108, 114, 156, 122, 219, 95, 130, 112, 84, 29, 192, 73, 152, 0, 17, 151, 33, 12, 198, 90, 13, 15, 141, 99, 210, 14, 184, 100, 27, 63, 7, 216, 249, 28, 153, 83, 171, 211, 97, 206, 132, 47, 114, 51, 176, 1, 1, 24, 239, 178, 2, 89, 213, 163, 247, 234, 7, 87, 135, 77, 188, 133, 221, 255, 239, 213, 105, 131, 134, 208, 238, 55, 235, 197, 206, 226, 243, 25, 69, 93, 99, 108, 100, 143, 197, 233, 175, 158, 82, 135, 136, 20, 90, 184, 133, 131, 188, 201, 45, 78, 96, 25, 100, 221, 197, 57, 247, 148, 88, 143, 128, 81, 84, 102, 6, 216, 165 }
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 886, DateTimeKind.Local).AddTicks(8138),
                            Email = "VerhofstadDeZeemlap@europeesemailadres.com",
                            FirstName = "Verhofstad",
                            ImageUrl = "https://robohash.org/Zeemlap",
                            IsAdmin = false,
                            LastName = "Zeemlap",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 886, DateTimeKind.Local).AddTicks(8138),
                            PasswordHash = new byte[] { 77, 194, 166, 27, 170, 163, 13, 247, 238, 164, 255, 84, 45, 232, 135, 161, 157, 60, 69, 218, 37, 57, 183, 198, 251, 143, 71, 29, 158, 108, 22, 203, 166, 243, 53, 63, 177, 208, 251, 182, 41, 227, 6, 149, 114, 198, 169, 177, 203, 69, 134, 86, 232, 165, 20, 160, 230, 43, 133, 33, 202, 34, 90, 39 },
                            PasswordSalt = new byte[] { 28, 156, 34, 199, 227, 145, 199, 132, 30, 11, 9, 108, 114, 156, 122, 219, 95, 130, 112, 84, 29, 192, 73, 152, 0, 17, 151, 33, 12, 198, 90, 13, 15, 141, 99, 210, 14, 184, 100, 27, 63, 7, 216, 249, 28, 153, 83, 171, 211, 97, 206, 132, 47, 114, 51, 176, 1, 1, 24, 239, 178, 2, 89, 213, 163, 247, 234, 7, 87, 135, 77, 188, 133, 221, 255, 239, 213, 105, 131, 134, 208, 238, 55, 235, 197, 206, 226, 243, 25, 69, 93, 99, 108, 100, 143, 197, 233, 175, 158, 82, 135, 136, 20, 90, 184, 133, 131, 188, 201, 45, 78, 96, 25, 100, 221, 197, 57, 247, 148, 88, 143, 128, 81, 84, 102, 6, 216, 165 }
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 886, DateTimeKind.Local).AddTicks(8158),
                            Email = "Driesdentweedenmaarnidezelfden@mail.com",
                            FirstName = "Dries",
                            ImageUrl = "https://robohash.org/Dries2",
                            IsAdmin = false,
                            LastName = "VanKorteNekke",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 886, DateTimeKind.Local).AddTicks(8158),
                            PasswordHash = new byte[] { 77, 194, 166, 27, 170, 163, 13, 247, 238, 164, 255, 84, 45, 232, 135, 161, 157, 60, 69, 218, 37, 57, 183, 198, 251, 143, 71, 29, 158, 108, 22, 203, 166, 243, 53, 63, 177, 208, 251, 182, 41, 227, 6, 149, 114, 198, 169, 177, 203, 69, 134, 86, 232, 165, 20, 160, 230, 43, 133, 33, 202, 34, 90, 39 },
                            PasswordSalt = new byte[] { 28, 156, 34, 199, 227, 145, 199, 132, 30, 11, 9, 108, 114, 156, 122, 219, 95, 130, 112, 84, 29, 192, 73, 152, 0, 17, 151, 33, 12, 198, 90, 13, 15, 141, 99, 210, 14, 184, 100, 27, 63, 7, 216, 249, 28, 153, 83, 171, 211, 97, 206, 132, 47, 114, 51, 176, 1, 1, 24, 239, 178, 2, 89, 213, 163, 247, 234, 7, 87, 135, 77, 188, 133, 221, 255, 239, 213, 105, 131, 134, 208, 238, 55, 235, 197, 206, 226, 243, 25, 69, 93, 99, 108, 100, 143, 197, 233, 175, 158, 82, 135, 136, 20, 90, 184, 133, 131, 188, 201, 45, 78, 96, 25, 100, 221, 197, 57, 247, 148, 88, 143, 128, 81, 84, 102, 6, 216, 165 }
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 886, DateTimeKind.Local).AddTicks(8177),
                            Email = "Joyce@mail.com",
                            FirstName = "Joyce",
                            ImageUrl = "https://robohash.org/Tomatenplukker",
                            IsAdmin = false,
                            LastName = "Tomatenplukker",
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 886, DateTimeKind.Local).AddTicks(8177),
                            PasswordHash = new byte[] { 77, 194, 166, 27, 170, 163, 13, 247, 238, 164, 255, 84, 45, 232, 135, 161, 157, 60, 69, 218, 37, 57, 183, 198, 251, 143, 71, 29, 158, 108, 22, 203, 166, 243, 53, 63, 177, 208, 251, 182, 41, 227, 6, 149, 114, 198, 169, 177, 203, 69, 134, 86, 232, 165, 20, 160, 230, 43, 133, 33, 202, 34, 90, 39 },
                            PasswordSalt = new byte[] { 28, 156, 34, 199, 227, 145, 199, 132, 30, 11, 9, 108, 114, 156, 122, 219, 95, 130, 112, 84, 29, 192, 73, 152, 0, 17, 151, 33, 12, 198, 90, 13, 15, 141, 99, 210, 14, 184, 100, 27, 63, 7, 216, 249, 28, 153, 83, 171, 211, 97, 206, 132, 47, 114, 51, 176, 1, 1, 24, 239, 178, 2, 89, 213, 163, 247, 234, 7, 87, 135, 77, 188, 133, 221, 255, 239, 213, 105, 131, 134, 208, 238, 55, 235, 197, 206, 226, 243, 25, 69, 93, 99, 108, 100, 143, 197, 233, 175, 158, 82, 135, 136, 20, 90, 184, 133, 131, 188, 201, 45, 78, 96, 25, 100, 221, 197, 57, 247, 148, 88, 143, 128, 81, 84, 102, 6, 216, 165 }
                        });
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("VAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 890, DateTimeKind.Local).AddTicks(3242),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 890, DateTimeKind.Local).AddTicks(3242),
                            UserId = 1,
                            VAmount = 200m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 890, DateTimeKind.Local).AddTicks(4479),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 890, DateTimeKind.Local).AddTicks(4479),
                            UserId = 2,
                            VAmount = 347m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 890, DateTimeKind.Local).AddTicks(4495),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 890, DateTimeKind.Local).AddTicks(4495),
                            UserId = 3,
                            VAmount = 65m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 890, DateTimeKind.Local).AddTicks(4500),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 890, DateTimeKind.Local).AddTicks(4500),
                            UserId = 4,
                            VAmount = 42m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 890, DateTimeKind.Local).AddTicks(4503),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 890, DateTimeKind.Local).AddTicks(4503),
                            UserId = 5,
                            VAmount = 753m
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 890, DateTimeKind.Local).AddTicks(4506),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 890, DateTimeKind.Local).AddTicks(4506),
                            UserId = 6,
                            VAmount = 36m
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 890, DateTimeKind.Local).AddTicks(4509),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 890, DateTimeKind.Local).AddTicks(4509),
                            UserId = 7,
                            VAmount = 12m
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 890, DateTimeKind.Local).AddTicks(4512),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 890, DateTimeKind.Local).AddTicks(4512),
                            UserId = 8,
                            VAmount = 654m
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 890, DateTimeKind.Local).AddTicks(4515),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 890, DateTimeKind.Local).AddTicks(4515),
                            UserId = 9,
                            VAmount = 357m
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 890, DateTimeKind.Local).AddTicks(4517),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 890, DateTimeKind.Local).AddTicks(4517),
                            UserId = 10,
                            VAmount = 124m
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 890, DateTimeKind.Local).AddTicks(4521),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 890, DateTimeKind.Local).AddTicks(4521),
                            UserId = 11,
                            VAmount = 269m
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 890, DateTimeKind.Local).AddTicks(4523),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 890, DateTimeKind.Local).AddTicks(4523),
                            UserId = 12,
                            VAmount = 57m
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 5, 18, 15, 55, 38, 890, DateTimeKind.Local).AddTicks(4527),
                            ModifiedAt = new DateTime(2021, 5, 18, 15, 55, 38, 890, DateTimeKind.Local).AddTicks(4527),
                            UserId = 13,
                            VAmount = 204m
                        });
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Address", b =>
                {
                    b.HasOne("VeggieSwapServer.Data.Entities.User", "User")
                        .WithOne("Address")
                        .HasForeignKey("VeggieSwapServer.Data.Entities.Address", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Purchase", b =>
                {
                    b.HasOne("VeggieSwapServer.Data.Entities.Wallet", "Wallet")
                        .WithMany("Purchases")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.TradeItem", b =>
                {
                    b.HasOne("VeggieSwapServer.Data.Entities.Resource", "Resource")
                        .WithMany("TradeItems")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeggieSwapServer.Data.Entities.Trade", "Trade")
                        .WithMany("TradeItems")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeggieSwapServer.Data.Entities.User", "User")
                        .WithMany("TradeItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("Trade");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Wallet", b =>
                {
                    b.HasOne("VeggieSwapServer.Data.Entities.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("VeggieSwapServer.Data.Entities.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Resource", b =>
                {
                    b.Navigation("TradeItems");
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Trade", b =>
                {
                    b.Navigation("TradeItems");
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.User", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("TradeItems");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Wallet", b =>
                {
                    b.Navigation("Purchases");
                });
#pragma warning restore 612, 618
        }
    }
}
