// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeggieSwapServer.Data;

namespace VeggieSwapServer.Data.Migrations
{
    [DbContext(typeof(VeggieSwapServerContext))]
    [Migration("20210518180824_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 924, DateTimeKind.Local).AddTicks(9337),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 924, DateTimeKind.Local).AddTicks(9337),
                            PostalCode = 9000,
                            StreetName = "Anti-Veggiestraat",
                            StreetNumber = 89,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 925, DateTimeKind.Local).AddTicks(2171),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 925, DateTimeKind.Local).AddTicks(2171),
                            PostalCode = 9000,
                            StreetName = "Pieterstreaat",
                            StreetNumber = 45,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 925, DateTimeKind.Local).AddTicks(2190),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 925, DateTimeKind.Local).AddTicks(2190),
                            PostalCode = 9000,
                            StreetName = "Nickstraat",
                            StreetNumber = 74,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 925, DateTimeKind.Local).AddTicks(2194),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 925, DateTimeKind.Local).AddTicks(2194),
                            PostalCode = 1000,
                            StreetName = "Driesstraat",
                            StreetNumber = 66,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 925, DateTimeKind.Local).AddTicks(2198),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 925, DateTimeKind.Local).AddTicks(2198),
                            PostalCode = 2000,
                            StreetName = "Kobestraat",
                            StreetNumber = 85,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 925, DateTimeKind.Local).AddTicks(2201),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 925, DateTimeKind.Local).AddTicks(2201),
                            PostalCode = 1000,
                            StreetName = "Lookbroodjesstraat",
                            StreetNumber = 43,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 925, DateTimeKind.Local).AddTicks(2204),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 925, DateTimeKind.Local).AddTicks(2204),
                            PostalCode = 9050,
                            StreetName = "Greenpeacestraat",
                            StreetNumber = 1,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 925, DateTimeKind.Local).AddTicks(2208),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 925, DateTimeKind.Local).AddTicks(2208),
                            PostalCode = 1000,
                            StreetName = "Kotsvisstraat",
                            StreetNumber = 96,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 925, DateTimeKind.Local).AddTicks(2212),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 925, DateTimeKind.Local).AddTicks(2212),
                            PostalCode = 2000,
                            StreetName = "Greenlivesmattertoostraat",
                            StreetNumber = 420,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 925, DateTimeKind.Local).AddTicks(2215),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 925, DateTimeKind.Local).AddTicks(2215),
                            PostalCode = 9070,
                            StreetName = "Geenpolitiekinhetprojectstraat",
                            StreetNumber = 200,
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 925, DateTimeKind.Local).AddTicks(2218),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 925, DateTimeKind.Local).AddTicks(2218),
                            PostalCode = 9500,
                            StreetName = "Kalfslapjesstraat",
                            StreetNumber = 32,
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 925, DateTimeKind.Local).AddTicks(2221),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 925, DateTimeKind.Local).AddTicks(2221),
                            PostalCode = 1000,
                            StreetName = "Blacklivesmatterstraat",
                            StreetNumber = 78,
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 925, DateTimeKind.Local).AddTicks(2224),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 925, DateTimeKind.Local).AddTicks(2224),
                            PostalCode = 9020,
                            StreetName = "Worstenbroodjesstraat",
                            StreetNumber = 4,
                            UserId = 13
                        });
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EuroAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("VAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("Purchases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 931, DateTimeKind.Local).AddTicks(6809),
                            EuroAmount = 6.9m,
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 931, DateTimeKind.Local).AddTicks(6809),
                            VAmount = 69m,
                            WalletId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 931, DateTimeKind.Local).AddTicks(9668),
                            EuroAmount = 2m,
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 931, DateTimeKind.Local).AddTicks(9668),
                            VAmount = 20m,
                            WalletId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 931, DateTimeKind.Local).AddTicks(9685),
                            EuroAmount = 42m,
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 931, DateTimeKind.Local).AddTicks(9685),
                            VAmount = 420m,
                            WalletId = 5
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 931, DateTimeKind.Local).AddTicks(9689),
                            EuroAmount = 10m,
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 931, DateTimeKind.Local).AddTicks(9689),
                            VAmount = 100m,
                            WalletId = 6
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 931, DateTimeKind.Local).AddTicks(9692),
                            EuroAmount = 3.6m,
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 931, DateTimeKind.Local).AddTicks(9692),
                            VAmount = 36m,
                            WalletId = 12
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 931, DateTimeKind.Local).AddTicks(9927),
                            EuroAmount = 7.8m,
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 931, DateTimeKind.Local).AddTicks(9927),
                            VAmount = 78m,
                            WalletId = 10
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 931, DateTimeKind.Local).AddTicks(9932),
                            EuroAmount = 9.8m,
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 931, DateTimeKind.Local).AddTicks(9932),
                            VAmount = 98m,
                            WalletId = 9
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 931, DateTimeKind.Local).AddTicks(9935),
                            EuroAmount = 5m,
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 931, DateTimeKind.Local).AddTicks(9935),
                            VAmount = 50m,
                            WalletId = 7
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 931, DateTimeKind.Local).AddTicks(9940),
                            EuroAmount = 13m,
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 931, DateTimeKind.Local).AddTicks(9940),
                            VAmount = 130m,
                            WalletId = 3
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 931, DateTimeKind.Local).AddTicks(9945),
                            EuroAmount = 2m,
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 931, DateTimeKind.Local).AddTicks(9945),
                            VAmount = 20m,
                            WalletId = 4
                        });
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 927, DateTimeKind.Local).AddTicks(9229),
                            ImageUrl = "apples.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 927, DateTimeKind.Local).AddTicks(9229),
                            Name = "apples"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(454),
                            ImageUrl = "artichokes.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(454),
                            Name = "artichokes"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(469),
                            ImageUrl = "asparaguses.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(469),
                            Name = "asparaguses"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(473),
                            ImageUrl = "bananas.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(473),
                            Name = "bananas"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(476),
                            ImageUrl = "bell-peppers.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(476),
                            Name = "bell-peppers"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(479),
                            ImageUrl = "blueberries.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(479),
                            Name = "blueberries"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(482),
                            ImageUrl = "bok-choy.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(482),
                            Name = "bok-choy"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(486),
                            ImageUrl = "broccoli.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(486),
                            Name = "broccoli"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(489),
                            ImageUrl = "brussels-sprouts.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(489),
                            Name = "brussels-sprouts"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(492),
                            ImageUrl = "carrots.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(492),
                            Name = "carrots"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(495),
                            ImageUrl = "cherries.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(495),
                            Name = "cherries"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(498),
                            ImageUrl = "chilis.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(498),
                            Name = "chilis"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(502),
                            ImageUrl = "coconuts.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(502),
                            Name = "coconuts"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(504),
                            ImageUrl = "coriander.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(504),
                            Name = "coriander"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(508),
                            ImageUrl = "corn.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(508),
                            Name = "corn"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(511),
                            ImageUrl = "cucumbers.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(511),
                            Name = "cucumbers"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(514),
                            ImageUrl = "dragon-fruits.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(514),
                            Name = "dragon-fruits"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(517),
                            ImageUrl = "durians.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(517),
                            Name = "durians"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(520),
                            ImageUrl = "eggplants.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(520),
                            Name = "eggplants"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(523),
                            ImageUrl = "garlic.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(523),
                            Name = "garlic"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(526),
                            ImageUrl = "grapes.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(526),
                            Name = "grapes"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(529),
                            ImageUrl = "guavas.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(529),
                            Name = "guavas"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(533),
                            ImageUrl = "kiwis.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(533),
                            Name = "kiwis"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(536),
                            ImageUrl = "lemons.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(536),
                            Name = "lemons"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(540),
                            ImageUrl = "mangos.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(540),
                            Name = "mangos"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(542),
                            ImageUrl = "mangosteens.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(542),
                            Name = "mangosteens"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(546),
                            ImageUrl = "melons.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(546),
                            Name = "melons"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(549),
                            ImageUrl = "mushrooms.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(549),
                            Name = "mushrooms"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(623),
                            ImageUrl = "olives.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(623),
                            Name = "olives"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(626),
                            ImageUrl = "oranges.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(626),
                            Name = "oranges"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(629),
                            ImageUrl = "papayas.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(629),
                            Name = "papayas"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(632),
                            ImageUrl = "peaches.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(632),
                            Name = "peaches"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(635),
                            ImageUrl = "pears.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(635),
                            Name = "pears"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(638),
                            ImageUrl = "peas.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(638),
                            Name = "peas"
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(641),
                            ImageUrl = "pineapples.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(641),
                            Name = "pineapples"
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(644),
                            ImageUrl = "pomegranates.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(644),
                            Name = "pomegranates"
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(646),
                            ImageUrl = "potatoes.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(646),
                            Name = "potatoes"
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(649),
                            ImageUrl = "pumpkins.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(649),
                            Name = "pumpkins"
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(652),
                            ImageUrl = "radish.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(652),
                            Name = "radish"
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(655),
                            ImageUrl = "radishes.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(655),
                            Name = "radishes"
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(658),
                            ImageUrl = "raspberries.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(658),
                            Name = "raspberries"
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(661),
                            ImageUrl = "salad.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(661),
                            Name = "salad"
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(664),
                            ImageUrl = "salads.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(664),
                            Name = "salads"
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(667),
                            ImageUrl = "scallions.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(667),
                            Name = "scallions"
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(669),
                            ImageUrl = "spinach.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(669),
                            Name = "spinach"
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(672),
                            ImageUrl = "star-fruits.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(672),
                            Name = "star-fruits"
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(675),
                            ImageUrl = "strawberries.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(675),
                            Name = "strawberries"
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(678),
                            ImageUrl = "sweet-potatoes.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(678),
                            Name = "sweet-potatoes"
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(681),
                            ImageUrl = "tomatoes.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(681),
                            Name = "tomatoes"
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(683),
                            ImageUrl = "watermelons.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(683),
                            Name = "watermelons"
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(686),
                            ImageUrl = "v-coin.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(686),
                            Name = "v-coin"
                        });
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProposerId")
                        .HasColumnType("int");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProposerId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("Trades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Completed = true,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(5811),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(5811),
                            ProposerId = 2,
                            ReceiverId = 1
                        },
                        new
                        {
                            Id = 2,
                            Completed = false,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(8008),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(8008),
                            ProposerId = 3,
                            ReceiverId = 1
                        },
                        new
                        {
                            Id = 3,
                            Completed = false,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(8022),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(8022),
                            ProposerId = 4,
                            ReceiverId = 2
                        },
                        new
                        {
                            Id = 4,
                            Completed = false,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(8026),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(8026),
                            ProposerId = 5,
                            ReceiverId = 2
                        },
                        new
                        {
                            Id = 5,
                            Completed = false,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(8029),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(8029),
                            ProposerId = 1,
                            ReceiverId = 5
                        },
                        new
                        {
                            Id = 6,
                            Completed = false,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(8033),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 928, DateTimeKind.Local).AddTicks(8033),
                            ProposerId = 3,
                            ReceiverId = 1
                        });
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.TradeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<bool>("Sold")
                        .HasColumnType("bit");

                    b.Property<int?>("TradeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("TradeId");

                    b.HasIndex("UserId");

                    b.ToTable("TradeItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 2,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 929, DateTimeKind.Local).AddTicks(9772),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 929, DateTimeKind.Local).AddTicks(9772),
                            ResourceId = 51,
                            Sold = false,
                            UserId = 10
                        },
                        new
                        {
                            Id = 2,
                            Amount = 10,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(4365),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(4365),
                            ResourceId = 11,
                            Sold = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 3,
                            Amount = 50,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(4395),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(4395),
                            ResourceId = 32,
                            Sold = false,
                            UserId = 13
                        },
                        new
                        {
                            Id = 4,
                            Amount = 69,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(4399),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(4399),
                            ResourceId = 24,
                            Sold = false,
                            TradeId = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Amount = 45,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5064),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5064),
                            ResourceId = 45,
                            Sold = false,
                            TradeId = 5,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            Amount = 30,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5077),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5077),
                            ResourceId = 6,
                            Sold = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            Amount = 42,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5081),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5081),
                            ResourceId = 17,
                            Sold = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            Amount = 75,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5084),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5084),
                            ResourceId = 8,
                            Sold = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            Amount = 201,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5087),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5087),
                            ResourceId = 9,
                            Sold = false,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            Amount = 634,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5090),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5090),
                            ResourceId = 10,
                            Sold = false,
                            UserId = 9
                        },
                        new
                        {
                            Id = 11,
                            Amount = 20,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5093),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5093),
                            ResourceId = 17,
                            Sold = false,
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            Amount = 75,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5096),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5096),
                            ResourceId = 26,
                            Sold = false,
                            UserId = 13
                        },
                        new
                        {
                            Id = 13,
                            Amount = 69,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5099),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5099),
                            ResourceId = 19,
                            Sold = false,
                            UserId = 10
                        },
                        new
                        {
                            Id = 14,
                            Amount = 25,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5102),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5102),
                            ResourceId = 49,
                            Sold = true,
                            TradeId = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 15,
                            Amount = 35,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5107),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5107),
                            ResourceId = 50,
                            Sold = false,
                            TradeId = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 16,
                            Amount = 75,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5111),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5111),
                            ResourceId = 7,
                            Sold = false,
                            TradeId = 4,
                            UserId = 5
                        },
                        new
                        {
                            Id = 17,
                            Amount = 10,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5116),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5116),
                            ResourceId = 1,
                            Sold = false,
                            TradeId = 6,
                            UserId = 3
                        },
                        new
                        {
                            Id = 18,
                            Amount = 9,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5120),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5120),
                            ResourceId = 6,
                            Sold = true,
                            TradeId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 19,
                            Amount = 17,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5124),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5124),
                            ResourceId = 7,
                            Sold = false,
                            UserId = 12
                        },
                        new
                        {
                            Id = 20,
                            Amount = 30,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5128),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5128),
                            ResourceId = 36,
                            Sold = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 21,
                            Amount = 78,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5133),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5133),
                            ResourceId = 23,
                            Sold = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 22,
                            Amount = 69,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5138),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5138),
                            ResourceId = 27,
                            Sold = false,
                            UserId = 9
                        },
                        new
                        {
                            Id = 23,
                            Amount = 180,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5142),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5142),
                            ResourceId = 37,
                            Sold = true,
                            TradeId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 24,
                            Amount = 47,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5145),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5145),
                            ResourceId = 47,
                            Sold = true,
                            TradeId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 25,
                            Amount = 20,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5148),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5148),
                            ResourceId = 48,
                            Sold = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 26,
                            Amount = 10,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5153),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 930, DateTimeKind.Local).AddTicks(5153),
                            ResourceId = 39,
                            Sold = false,
                            UserId = 7
                        });
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 918, DateTimeKind.Local).AddTicks(1202),
                            Email = "Pieter@mail.com",
                            FirstName = "Pieter",
                            ImageUrl = "https://robohash.org/Pieter",
                            IsAdmin = true,
                            LastName = "Corp",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 918, DateTimeKind.Local).AddTicks(1202),
                            PasswordHash = new byte[] { 31, 148, 213, 107, 247, 60, 230, 64, 118, 149, 9, 31, 201, 181, 149, 62, 20, 29, 237, 30, 209, 214, 215, 106, 136, 255, 93, 228, 229, 31, 242, 144, 1, 103, 32, 229, 178, 102, 20, 136, 76, 6, 152, 167, 88, 5, 90, 38, 118, 214, 92, 10, 244, 180, 26, 229, 64, 215, 127, 193, 180, 62, 221, 17 },
                            PasswordSalt = new byte[] { 94, 188, 112, 201, 220, 80, 215, 18, 115, 227, 178, 233, 1, 81, 154, 126, 248, 237, 247, 227, 37, 208, 232, 203, 171, 123, 169, 241, 94, 38, 115, 127, 20, 13, 167, 209, 92, 86, 129, 119, 166, 9, 247, 48, 57, 244, 208, 38, 255, 76, 27, 201, 84, 35, 185, 81, 11, 66, 29, 138, 29, 214, 212, 2, 203, 69, 255, 67, 126, 215, 241, 85, 90, 127, 95, 125, 138, 20, 50, 162, 243, 179, 124, 172, 90, 107, 3, 124, 219, 6, 45, 46, 30, 0, 71, 21, 93, 171, 255, 56, 20, 162, 56, 145, 54, 34, 93, 42, 118, 36, 195, 147, 201, 199, 161, 111, 188, 105, 169, 171, 48, 184, 202, 119, 55, 66, 171, 250 }
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 922, DateTimeKind.Local).AddTicks(8024),
                            Email = "Nick@mail.com",
                            FirstName = "Nick",
                            ImageUrl = "https://robohash.org/Nick",
                            IsAdmin = true,
                            LastName = "Vr",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 922, DateTimeKind.Local).AddTicks(8024),
                            PasswordHash = new byte[] { 31, 148, 213, 107, 247, 60, 230, 64, 118, 149, 9, 31, 201, 181, 149, 62, 20, 29, 237, 30, 209, 214, 215, 106, 136, 255, 93, 228, 229, 31, 242, 144, 1, 103, 32, 229, 178, 102, 20, 136, 76, 6, 152, 167, 88, 5, 90, 38, 118, 214, 92, 10, 244, 180, 26, 229, 64, 215, 127, 193, 180, 62, 221, 17 },
                            PasswordSalt = new byte[] { 94, 188, 112, 201, 220, 80, 215, 18, 115, 227, 178, 233, 1, 81, 154, 126, 248, 237, 247, 227, 37, 208, 232, 203, 171, 123, 169, 241, 94, 38, 115, 127, 20, 13, 167, 209, 92, 86, 129, 119, 166, 9, 247, 48, 57, 244, 208, 38, 255, 76, 27, 201, 84, 35, 185, 81, 11, 66, 29, 138, 29, 214, 212, 2, 203, 69, 255, 67, 126, 215, 241, 85, 90, 127, 95, 125, 138, 20, 50, 162, 243, 179, 124, 172, 90, 107, 3, 124, 219, 6, 45, 46, 30, 0, 71, 21, 93, 171, 255, 56, 20, 162, 56, 145, 54, 34, 93, 42, 118, 36, 195, 147, 201, 199, 161, 111, 188, 105, 169, 171, 48, 184, 202, 119, 55, 66, 171, 250 }
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 922, DateTimeKind.Local).AddTicks(8243),
                            Email = "Kobe@mail.com",
                            FirstName = "Kobe",
                            ImageUrl = "https://robohash.org/Kobe",
                            IsAdmin = true,
                            LastName = "Delo",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 922, DateTimeKind.Local).AddTicks(8243),
                            PasswordHash = new byte[] { 31, 148, 213, 107, 247, 60, 230, 64, 118, 149, 9, 31, 201, 181, 149, 62, 20, 29, 237, 30, 209, 214, 215, 106, 136, 255, 93, 228, 229, 31, 242, 144, 1, 103, 32, 229, 178, 102, 20, 136, 76, 6, 152, 167, 88, 5, 90, 38, 118, 214, 92, 10, 244, 180, 26, 229, 64, 215, 127, 193, 180, 62, 221, 17 },
                            PasswordSalt = new byte[] { 94, 188, 112, 201, 220, 80, 215, 18, 115, 227, 178, 233, 1, 81, 154, 126, 248, 237, 247, 227, 37, 208, 232, 203, 171, 123, 169, 241, 94, 38, 115, 127, 20, 13, 167, 209, 92, 86, 129, 119, 166, 9, 247, 48, 57, 244, 208, 38, 255, 76, 27, 201, 84, 35, 185, 81, 11, 66, 29, 138, 29, 214, 212, 2, 203, 69, 255, 67, 126, 215, 241, 85, 90, 127, 95, 125, 138, 20, 50, 162, 243, 179, 124, 172, 90, 107, 3, 124, 219, 6, 45, 46, 30, 0, 71, 21, 93, 171, 255, 56, 20, 162, 56, 145, 54, 34, 93, 42, 118, 36, 195, 147, 201, 199, 161, 111, 188, 105, 169, 171, 48, 184, 202, 119, 55, 66, 171, 250 }
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 922, DateTimeKind.Local).AddTicks(8272),
                            Email = "Dries@mail.com",
                            FirstName = "Dries",
                            ImageUrl = "https://robohash.org/Dries",
                            IsAdmin = true,
                            LastName = "Maes",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 922, DateTimeKind.Local).AddTicks(8272),
                            PasswordHash = new byte[] { 31, 148, 213, 107, 247, 60, 230, 64, 118, 149, 9, 31, 201, 181, 149, 62, 20, 29, 237, 30, 209, 214, 215, 106, 136, 255, 93, 228, 229, 31, 242, 144, 1, 103, 32, 229, 178, 102, 20, 136, 76, 6, 152, 167, 88, 5, 90, 38, 118, 214, 92, 10, 244, 180, 26, 229, 64, 215, 127, 193, 180, 62, 221, 17 },
                            PasswordSalt = new byte[] { 94, 188, 112, 201, 220, 80, 215, 18, 115, 227, 178, 233, 1, 81, 154, 126, 248, 237, 247, 227, 37, 208, 232, 203, 171, 123, 169, 241, 94, 38, 115, 127, 20, 13, 167, 209, 92, 86, 129, 119, 166, 9, 247, 48, 57, 244, 208, 38, 255, 76, 27, 201, 84, 35, 185, 81, 11, 66, 29, 138, 29, 214, 212, 2, 203, 69, 255, 67, 126, 215, 241, 85, 90, 127, 95, 125, 138, 20, 50, 162, 243, 179, 124, 172, 90, 107, 3, 124, 219, 6, 45, 46, 30, 0, 71, 21, 93, 171, 255, 56, 20, 162, 56, 145, 54, 34, 93, 42, 118, 36, 195, 147, 201, 199, 161, 111, 188, 105, 169, 171, 48, 184, 202, 119, 55, 66, 171, 250 }
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 922, DateTimeKind.Local).AddTicks(8289),
                            Email = "BartjeWevertje@mail.com",
                            FirstName = "BartjeWevertje",
                            ImageUrl = "https://robohash.org/BartjeWevertje",
                            IsAdmin = false,
                            LastName = "Wevertje",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 922, DateTimeKind.Local).AddTicks(8289),
                            PasswordHash = new byte[] { 31, 148, 213, 107, 247, 60, 230, 64, 118, 149, 9, 31, 201, 181, 149, 62, 20, 29, 237, 30, 209, 214, 215, 106, 136, 255, 93, 228, 229, 31, 242, 144, 1, 103, 32, 229, 178, 102, 20, 136, 76, 6, 152, 167, 88, 5, 90, 38, 118, 214, 92, 10, 244, 180, 26, 229, 64, 215, 127, 193, 180, 62, 221, 17 },
                            PasswordSalt = new byte[] { 94, 188, 112, 201, 220, 80, 215, 18, 115, 227, 178, 233, 1, 81, 154, 126, 248, 237, 247, 227, 37, 208, 232, 203, 171, 123, 169, 241, 94, 38, 115, 127, 20, 13, 167, 209, 92, 86, 129, 119, 166, 9, 247, 48, 57, 244, 208, 38, 255, 76, 27, 201, 84, 35, 185, 81, 11, 66, 29, 138, 29, 214, 212, 2, 203, 69, 255, 67, 126, 215, 241, 85, 90, 127, 95, 125, 138, 20, 50, 162, 243, 179, 124, 172, 90, 107, 3, 124, 219, 6, 45, 46, 30, 0, 71, 21, 93, 171, 255, 56, 20, 162, 56, 145, 54, 34, 93, 42, 118, 36, 195, 147, 201, 199, 161, 111, 188, 105, 169, 171, 48, 184, 202, 119, 55, 66, 171, 250 }
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 922, DateTimeKind.Local).AddTicks(8306),
                            Email = "Stofzuiger@mail.com",
                            FirstName = "Stofzuiger",
                            ImageUrl = "https://robohash.org/Stofzuiger",
                            IsAdmin = false,
                            LastName = "Zuiger",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 922, DateTimeKind.Local).AddTicks(8306),
                            PasswordHash = new byte[] { 31, 148, 213, 107, 247, 60, 230, 64, 118, 149, 9, 31, 201, 181, 149, 62, 20, 29, 237, 30, 209, 214, 215, 106, 136, 255, 93, 228, 229, 31, 242, 144, 1, 103, 32, 229, 178, 102, 20, 136, 76, 6, 152, 167, 88, 5, 90, 38, 118, 214, 92, 10, 244, 180, 26, 229, 64, 215, 127, 193, 180, 62, 221, 17 },
                            PasswordSalt = new byte[] { 94, 188, 112, 201, 220, 80, 215, 18, 115, 227, 178, 233, 1, 81, 154, 126, 248, 237, 247, 227, 37, 208, 232, 203, 171, 123, 169, 241, 94, 38, 115, 127, 20, 13, 167, 209, 92, 86, 129, 119, 166, 9, 247, 48, 57, 244, 208, 38, 255, 76, 27, 201, 84, 35, 185, 81, 11, 66, 29, 138, 29, 214, 212, 2, 203, 69, 255, 67, 126, 215, 241, 85, 90, 127, 95, 125, 138, 20, 50, 162, 243, 179, 124, 172, 90, 107, 3, 124, 219, 6, 45, 46, 30, 0, 71, 21, 93, 171, 255, 56, 20, 162, 56, 145, 54, 34, 93, 42, 118, 36, 195, 147, 201, 199, 161, 111, 188, 105, 169, 171, 48, 184, 202, 119, 55, 66, 171, 250 }
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 922, DateTimeKind.Local).AddTicks(8485),
                            Email = "Dirk@mail.com",
                            FirstName = "Dirk",
                            ImageUrl = "https://robohash.org/Dirk",
                            IsAdmin = false,
                            LastName = "Visser",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 922, DateTimeKind.Local).AddTicks(8485),
                            PasswordHash = new byte[] { 31, 148, 213, 107, 247, 60, 230, 64, 118, 149, 9, 31, 201, 181, 149, 62, 20, 29, 237, 30, 209, 214, 215, 106, 136, 255, 93, 228, 229, 31, 242, 144, 1, 103, 32, 229, 178, 102, 20, 136, 76, 6, 152, 167, 88, 5, 90, 38, 118, 214, 92, 10, 244, 180, 26, 229, 64, 215, 127, 193, 180, 62, 221, 17 },
                            PasswordSalt = new byte[] { 94, 188, 112, 201, 220, 80, 215, 18, 115, 227, 178, 233, 1, 81, 154, 126, 248, 237, 247, 227, 37, 208, 232, 203, 171, 123, 169, 241, 94, 38, 115, 127, 20, 13, 167, 209, 92, 86, 129, 119, 166, 9, 247, 48, 57, 244, 208, 38, 255, 76, 27, 201, 84, 35, 185, 81, 11, 66, 29, 138, 29, 214, 212, 2, 203, 69, 255, 67, 126, 215, 241, 85, 90, 127, 95, 125, 138, 20, 50, 162, 243, 179, 124, 172, 90, 107, 3, 124, 219, 6, 45, 46, 30, 0, 71, 21, 93, 171, 255, 56, 20, 162, 56, 145, 54, 34, 93, 42, 118, 36, 195, 147, 201, 199, 161, 111, 188, 105, 169, 171, 48, 184, 202, 119, 55, 66, 171, 250 }
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 922, DateTimeKind.Local).AddTicks(8505),
                            Email = "Andreas@mail.com",
                            FirstName = "Andreas",
                            ImageUrl = "https://robohash.org/Andreas",
                            IsAdmin = false,
                            LastName = "VanGrieken",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 922, DateTimeKind.Local).AddTicks(8505),
                            PasswordHash = new byte[] { 31, 148, 213, 107, 247, 60, 230, 64, 118, 149, 9, 31, 201, 181, 149, 62, 20, 29, 237, 30, 209, 214, 215, 106, 136, 255, 93, 228, 229, 31, 242, 144, 1, 103, 32, 229, 178, 102, 20, 136, 76, 6, 152, 167, 88, 5, 90, 38, 118, 214, 92, 10, 244, 180, 26, 229, 64, 215, 127, 193, 180, 62, 221, 17 },
                            PasswordSalt = new byte[] { 94, 188, 112, 201, 220, 80, 215, 18, 115, 227, 178, 233, 1, 81, 154, 126, 248, 237, 247, 227, 37, 208, 232, 203, 171, 123, 169, 241, 94, 38, 115, 127, 20, 13, 167, 209, 92, 86, 129, 119, 166, 9, 247, 48, 57, 244, 208, 38, 255, 76, 27, 201, 84, 35, 185, 81, 11, 66, 29, 138, 29, 214, 212, 2, 203, 69, 255, 67, 126, 215, 241, 85, 90, 127, 95, 125, 138, 20, 50, 162, 243, 179, 124, 172, 90, 107, 3, 124, 219, 6, 45, 46, 30, 0, 71, 21, 93, 171, 255, 56, 20, 162, 56, 145, 54, 34, 93, 42, 118, 36, 195, 147, 201, 199, 161, 111, 188, 105, 169, 171, 48, 184, 202, 119, 55, 66, 171, 250 }
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 922, DateTimeKind.Local).AddTicks(8521),
                            Email = "Mihiel@mail.com",
                            FirstName = "Mihiel",
                            ImageUrl = "https://robohash.org/Mihiel",
                            IsAdmin = false,
                            LastName = "Mihoen",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 922, DateTimeKind.Local).AddTicks(8521),
                            PasswordHash = new byte[] { 31, 148, 213, 107, 247, 60, 230, 64, 118, 149, 9, 31, 201, 181, 149, 62, 20, 29, 237, 30, 209, 214, 215, 106, 136, 255, 93, 228, 229, 31, 242, 144, 1, 103, 32, 229, 178, 102, 20, 136, 76, 6, 152, 167, 88, 5, 90, 38, 118, 214, 92, 10, 244, 180, 26, 229, 64, 215, 127, 193, 180, 62, 221, 17 },
                            PasswordSalt = new byte[] { 94, 188, 112, 201, 220, 80, 215, 18, 115, 227, 178, 233, 1, 81, 154, 126, 248, 237, 247, 227, 37, 208, 232, 203, 171, 123, 169, 241, 94, 38, 115, 127, 20, 13, 167, 209, 92, 86, 129, 119, 166, 9, 247, 48, 57, 244, 208, 38, 255, 76, 27, 201, 84, 35, 185, 81, 11, 66, 29, 138, 29, 214, 212, 2, 203, 69, 255, 67, 126, 215, 241, 85, 90, 127, 95, 125, 138, 20, 50, 162, 243, 179, 124, 172, 90, 107, 3, 124, 219, 6, 45, 46, 30, 0, 71, 21, 93, 171, 255, 56, 20, 162, 56, 145, 54, 34, 93, 42, 118, 36, 195, 147, 201, 199, 161, 111, 188, 105, 169, 171, 48, 184, 202, 119, 55, 66, 171, 250 }
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 922, DateTimeKind.Local).AddTicks(8537),
                            Email = "Luc@mail.com",
                            FirstName = "Luc",
                            ImageUrl = "https://robohash.org/Luc",
                            IsAdmin = false,
                            LastName = "DeHaantje",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 922, DateTimeKind.Local).AddTicks(8537),
                            PasswordHash = new byte[] { 31, 148, 213, 107, 247, 60, 230, 64, 118, 149, 9, 31, 201, 181, 149, 62, 20, 29, 237, 30, 209, 214, 215, 106, 136, 255, 93, 228, 229, 31, 242, 144, 1, 103, 32, 229, 178, 102, 20, 136, 76, 6, 152, 167, 88, 5, 90, 38, 118, 214, 92, 10, 244, 180, 26, 229, 64, 215, 127, 193, 180, 62, 221, 17 },
                            PasswordSalt = new byte[] { 94, 188, 112, 201, 220, 80, 215, 18, 115, 227, 178, 233, 1, 81, 154, 126, 248, 237, 247, 227, 37, 208, 232, 203, 171, 123, 169, 241, 94, 38, 115, 127, 20, 13, 167, 209, 92, 86, 129, 119, 166, 9, 247, 48, 57, 244, 208, 38, 255, 76, 27, 201, 84, 35, 185, 81, 11, 66, 29, 138, 29, 214, 212, 2, 203, 69, 255, 67, 126, 215, 241, 85, 90, 127, 95, 125, 138, 20, 50, 162, 243, 179, 124, 172, 90, 107, 3, 124, 219, 6, 45, 46, 30, 0, 71, 21, 93, 171, 255, 56, 20, 162, 56, 145, 54, 34, 93, 42, 118, 36, 195, 147, 201, 199, 161, 111, 188, 105, 169, 171, 48, 184, 202, 119, 55, 66, 171, 250 }
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 922, DateTimeKind.Local).AddTicks(8552),
                            Email = "VerhofstadDeZeemlap@europeesemailadres.com",
                            FirstName = "Verhofstad",
                            ImageUrl = "https://robohash.org/Zeemlap",
                            IsAdmin = false,
                            LastName = "Zeemlap",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 922, DateTimeKind.Local).AddTicks(8552),
                            PasswordHash = new byte[] { 31, 148, 213, 107, 247, 60, 230, 64, 118, 149, 9, 31, 201, 181, 149, 62, 20, 29, 237, 30, 209, 214, 215, 106, 136, 255, 93, 228, 229, 31, 242, 144, 1, 103, 32, 229, 178, 102, 20, 136, 76, 6, 152, 167, 88, 5, 90, 38, 118, 214, 92, 10, 244, 180, 26, 229, 64, 215, 127, 193, 180, 62, 221, 17 },
                            PasswordSalt = new byte[] { 94, 188, 112, 201, 220, 80, 215, 18, 115, 227, 178, 233, 1, 81, 154, 126, 248, 237, 247, 227, 37, 208, 232, 203, 171, 123, 169, 241, 94, 38, 115, 127, 20, 13, 167, 209, 92, 86, 129, 119, 166, 9, 247, 48, 57, 244, 208, 38, 255, 76, 27, 201, 84, 35, 185, 81, 11, 66, 29, 138, 29, 214, 212, 2, 203, 69, 255, 67, 126, 215, 241, 85, 90, 127, 95, 125, 138, 20, 50, 162, 243, 179, 124, 172, 90, 107, 3, 124, 219, 6, 45, 46, 30, 0, 71, 21, 93, 171, 255, 56, 20, 162, 56, 145, 54, 34, 93, 42, 118, 36, 195, 147, 201, 199, 161, 111, 188, 105, 169, 171, 48, 184, 202, 119, 55, 66, 171, 250 }
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 922, DateTimeKind.Local).AddTicks(8568),
                            Email = "Driesdentweedenmaarnidezelfden@mail.com",
                            FirstName = "Dries",
                            ImageUrl = "https://robohash.org/Dries2",
                            IsAdmin = false,
                            LastName = "VanKorteNekke",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 922, DateTimeKind.Local).AddTicks(8568),
                            PasswordHash = new byte[] { 31, 148, 213, 107, 247, 60, 230, 64, 118, 149, 9, 31, 201, 181, 149, 62, 20, 29, 237, 30, 209, 214, 215, 106, 136, 255, 93, 228, 229, 31, 242, 144, 1, 103, 32, 229, 178, 102, 20, 136, 76, 6, 152, 167, 88, 5, 90, 38, 118, 214, 92, 10, 244, 180, 26, 229, 64, 215, 127, 193, 180, 62, 221, 17 },
                            PasswordSalt = new byte[] { 94, 188, 112, 201, 220, 80, 215, 18, 115, 227, 178, 233, 1, 81, 154, 126, 248, 237, 247, 227, 37, 208, 232, 203, 171, 123, 169, 241, 94, 38, 115, 127, 20, 13, 167, 209, 92, 86, 129, 119, 166, 9, 247, 48, 57, 244, 208, 38, 255, 76, 27, 201, 84, 35, 185, 81, 11, 66, 29, 138, 29, 214, 212, 2, 203, 69, 255, 67, 126, 215, 241, 85, 90, 127, 95, 125, 138, 20, 50, 162, 243, 179, 124, 172, 90, 107, 3, 124, 219, 6, 45, 46, 30, 0, 71, 21, 93, 171, 255, 56, 20, 162, 56, 145, 54, 34, 93, 42, 118, 36, 195, 147, 201, 199, 161, 111, 188, 105, 169, 171, 48, 184, 202, 119, 55, 66, 171, 250 }
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 922, DateTimeKind.Local).AddTicks(8584),
                            Email = "Joyce@mail.com",
                            FirstName = "Joyce",
                            ImageUrl = "https://robohash.org/Tomatenplukker",
                            IsAdmin = false,
                            LastName = "Tomatenplukker",
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 922, DateTimeKind.Local).AddTicks(8584),
                            PasswordHash = new byte[] { 31, 148, 213, 107, 247, 60, 230, 64, 118, 149, 9, 31, 201, 181, 149, 62, 20, 29, 237, 30, 209, 214, 215, 106, 136, 255, 93, 228, 229, 31, 242, 144, 1, 103, 32, 229, 178, 102, 20, 136, 76, 6, 152, 167, 88, 5, 90, 38, 118, 214, 92, 10, 244, 180, 26, 229, 64, 215, 127, 193, 180, 62, 221, 17 },
                            PasswordSalt = new byte[] { 94, 188, 112, 201, 220, 80, 215, 18, 115, 227, 178, 233, 1, 81, 154, 126, 248, 237, 247, 227, 37, 208, 232, 203, 171, 123, 169, 241, 94, 38, 115, 127, 20, 13, 167, 209, 92, 86, 129, 119, 166, 9, 247, 48, 57, 244, 208, 38, 255, 76, 27, 201, 84, 35, 185, 81, 11, 66, 29, 138, 29, 214, 212, 2, 203, 69, 255, 67, 126, 215, 241, 85, 90, 127, 95, 125, 138, 20, 50, 162, 243, 179, 124, 172, 90, 107, 3, 124, 219, 6, 45, 46, 30, 0, 71, 21, 93, 171, 255, 56, 20, 162, 56, 145, 54, 34, 93, 42, 118, 36, 195, 147, 201, 199, 161, 111, 188, 105, 169, 171, 48, 184, 202, 119, 55, 66, 171, 250 }
                        });
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("VAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 925, DateTimeKind.Local).AddTicks(9410),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 925, DateTimeKind.Local).AddTicks(9410),
                            UserId = 1,
                            VAmount = 200m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 926, DateTimeKind.Local).AddTicks(1249),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 926, DateTimeKind.Local).AddTicks(1249),
                            UserId = 2,
                            VAmount = 347m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 926, DateTimeKind.Local).AddTicks(1396),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 926, DateTimeKind.Local).AddTicks(1396),
                            UserId = 3,
                            VAmount = 65m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 926, DateTimeKind.Local).AddTicks(1400),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 926, DateTimeKind.Local).AddTicks(1400),
                            UserId = 4,
                            VAmount = 42m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 926, DateTimeKind.Local).AddTicks(1404),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 926, DateTimeKind.Local).AddTicks(1404),
                            UserId = 5,
                            VAmount = 753m
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 926, DateTimeKind.Local).AddTicks(1510),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 926, DateTimeKind.Local).AddTicks(1510),
                            UserId = 6,
                            VAmount = 36m
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 926, DateTimeKind.Local).AddTicks(1514),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 926, DateTimeKind.Local).AddTicks(1514),
                            UserId = 7,
                            VAmount = 12m
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 926, DateTimeKind.Local).AddTicks(1517),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 926, DateTimeKind.Local).AddTicks(1517),
                            UserId = 8,
                            VAmount = 654m
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 926, DateTimeKind.Local).AddTicks(1520),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 926, DateTimeKind.Local).AddTicks(1520),
                            UserId = 9,
                            VAmount = 357m
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 926, DateTimeKind.Local).AddTicks(1523),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 926, DateTimeKind.Local).AddTicks(1523),
                            UserId = 10,
                            VAmount = 124m
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 926, DateTimeKind.Local).AddTicks(1526),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 926, DateTimeKind.Local).AddTicks(1526),
                            UserId = 11,
                            VAmount = 269m
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 926, DateTimeKind.Local).AddTicks(1530),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 926, DateTimeKind.Local).AddTicks(1530),
                            UserId = 12,
                            VAmount = 57m
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 5, 18, 20, 8, 23, 926, DateTimeKind.Local).AddTicks(1533),
                            ModifiedAt = new DateTime(2021, 5, 18, 20, 8, 23, 926, DateTimeKind.Local).AddTicks(1533),
                            UserId = 13,
                            VAmount = 204m
                        });
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Address", b =>
                {
                    b.HasOne("VeggieSwapServer.Data.Entities.User", "User")
                        .WithOne("Address")
                        .HasForeignKey("VeggieSwapServer.Data.Entities.Address", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Purchase", b =>
                {
                    b.HasOne("VeggieSwapServer.Data.Entities.Wallet", "Wallet")
                        .WithMany("Purchases")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Trade", b =>
                {
                    b.HasOne("VeggieSwapServer.Data.Entities.User", "Proposer")
                        .WithMany("TradeProposers")
                        .HasForeignKey("ProposerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeggieSwapServer.Data.Entities.User", "Receiver")
                        .WithMany("TradeReceivers")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proposer");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.TradeItem", b =>
                {
                    b.HasOne("VeggieSwapServer.Data.Entities.Resource", "Resource")
                        .WithMany("TradeItems")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeggieSwapServer.Data.Entities.Trade", "Trade")
                        .WithMany("TradeItems")
                        .HasForeignKey("TradeId");

                    b.HasOne("VeggieSwapServer.Data.Entities.User", "User")
                        .WithMany("TradeItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("Trade");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Wallet", b =>
                {
                    b.HasOne("VeggieSwapServer.Data.Entities.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("VeggieSwapServer.Data.Entities.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Resource", b =>
                {
                    b.Navigation("TradeItems");
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Trade", b =>
                {
                    b.Navigation("TradeItems");
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.User", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("TradeItems");

                    b.Navigation("TradeProposers");

                    b.Navigation("TradeReceivers");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Wallet", b =>
                {
                    b.Navigation("Purchases");
                });
#pragma warning restore 612, 618
        }
    }
}
