// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeggieSwapServer.Data;

namespace VeggieSwapServer.Data.Migrations
{
    [DbContext(typeof(VeggieSwapServerContext))]
    [Migration("20210518150454_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 789, DateTimeKind.Local).AddTicks(2984),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 789, DateTimeKind.Local).AddTicks(2984),
                            PostalCode = 9000,
                            StreetName = "Anti-Veggiestraat",
                            StreetNumber = 89,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 789, DateTimeKind.Local).AddTicks(5311),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 789, DateTimeKind.Local).AddTicks(5311),
                            PostalCode = 9000,
                            StreetName = "Pieterstreaat",
                            StreetNumber = 45,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 789, DateTimeKind.Local).AddTicks(5328),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 789, DateTimeKind.Local).AddTicks(5328),
                            PostalCode = 9000,
                            StreetName = "Nickstraat",
                            StreetNumber = 74,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 789, DateTimeKind.Local).AddTicks(5332),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 789, DateTimeKind.Local).AddTicks(5332),
                            PostalCode = 1000,
                            StreetName = "Driesstraat",
                            StreetNumber = 66,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 789, DateTimeKind.Local).AddTicks(5335),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 789, DateTimeKind.Local).AddTicks(5335),
                            PostalCode = 2000,
                            StreetName = "Kobestraat",
                            StreetNumber = 85,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 789, DateTimeKind.Local).AddTicks(5339),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 789, DateTimeKind.Local).AddTicks(5339),
                            PostalCode = 1000,
                            StreetName = "Lookbroodjesstraat",
                            StreetNumber = 43,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 789, DateTimeKind.Local).AddTicks(5342),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 789, DateTimeKind.Local).AddTicks(5342),
                            PostalCode = 9050,
                            StreetName = "Greenpeacestraat",
                            StreetNumber = 1,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 789, DateTimeKind.Local).AddTicks(5348),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 789, DateTimeKind.Local).AddTicks(5348),
                            PostalCode = 1000,
                            StreetName = "Kotsvisstraat",
                            StreetNumber = 96,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 789, DateTimeKind.Local).AddTicks(5352),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 789, DateTimeKind.Local).AddTicks(5352),
                            PostalCode = 2000,
                            StreetName = "Greenlivesmattertoostraat",
                            StreetNumber = 420,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 789, DateTimeKind.Local).AddTicks(5355),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 789, DateTimeKind.Local).AddTicks(5355),
                            PostalCode = 9070,
                            StreetName = "Geenpolitiekinhetprojectstraat",
                            StreetNumber = 200,
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 789, DateTimeKind.Local).AddTicks(5359),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 789, DateTimeKind.Local).AddTicks(5359),
                            PostalCode = 9500,
                            StreetName = "Kalfslapjesstraat",
                            StreetNumber = 32,
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 789, DateTimeKind.Local).AddTicks(5362),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 789, DateTimeKind.Local).AddTicks(5362),
                            PostalCode = 1000,
                            StreetName = "Blacklivesmatterstraat",
                            StreetNumber = 78,
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 789, DateTimeKind.Local).AddTicks(5365),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 789, DateTimeKind.Local).AddTicks(5365),
                            PostalCode = 9020,
                            StreetName = "Worstenbroodjesstraat",
                            StreetNumber = 4,
                            UserId = 13
                        });
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EuroAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("VAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("Purchases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 795, DateTimeKind.Local).AddTicks(8039),
                            EuroAmount = 6.9m,
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 795, DateTimeKind.Local).AddTicks(8039),
                            VAmount = 69m,
                            WalletId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 796, DateTimeKind.Local).AddTicks(213),
                            EuroAmount = 2m,
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 796, DateTimeKind.Local).AddTicks(213),
                            VAmount = 20m,
                            WalletId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 796, DateTimeKind.Local).AddTicks(243),
                            EuroAmount = 42m,
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 796, DateTimeKind.Local).AddTicks(243),
                            VAmount = 420m,
                            WalletId = 5
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 796, DateTimeKind.Local).AddTicks(247),
                            EuroAmount = 10m,
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 796, DateTimeKind.Local).AddTicks(247),
                            VAmount = 100m,
                            WalletId = 6
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 796, DateTimeKind.Local).AddTicks(256),
                            EuroAmount = 3.6m,
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 796, DateTimeKind.Local).AddTicks(256),
                            VAmount = 36m,
                            WalletId = 12
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 796, DateTimeKind.Local).AddTicks(259),
                            EuroAmount = 7.8m,
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 796, DateTimeKind.Local).AddTicks(259),
                            VAmount = 78m,
                            WalletId = 10
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 796, DateTimeKind.Local).AddTicks(262),
                            EuroAmount = 9.8m,
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 796, DateTimeKind.Local).AddTicks(262),
                            VAmount = 98m,
                            WalletId = 9
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 796, DateTimeKind.Local).AddTicks(265),
                            EuroAmount = 5m,
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 796, DateTimeKind.Local).AddTicks(265),
                            VAmount = 50m,
                            WalletId = 7
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 796, DateTimeKind.Local).AddTicks(268),
                            EuroAmount = 13m,
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 796, DateTimeKind.Local).AddTicks(268),
                            VAmount = 130m,
                            WalletId = 3
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 796, DateTimeKind.Local).AddTicks(272),
                            EuroAmount = 2m,
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 796, DateTimeKind.Local).AddTicks(272),
                            VAmount = 20m,
                            WalletId = 4
                        });
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 792, DateTimeKind.Local).AddTicks(7776),
                            ImageUrl = "apples.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 792, DateTimeKind.Local).AddTicks(7776),
                            Name = "apples"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2000),
                            ImageUrl = "artichokes.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2000),
                            Name = "artichokes"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2038),
                            ImageUrl = "asparaguses.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2038),
                            Name = "asparaguses"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2044),
                            ImageUrl = "bananas.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2044),
                            Name = "bananas"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2049),
                            ImageUrl = "bell-peppers.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2049),
                            Name = "bell-peppers"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2058),
                            ImageUrl = "blueberries.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2058),
                            Name = "blueberries"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2063),
                            ImageUrl = "bok-choy.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2063),
                            Name = "bok-choy"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2068),
                            ImageUrl = "broccoli.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2068),
                            Name = "broccoli"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2073),
                            ImageUrl = "brussels-sprouts.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2073),
                            Name = "brussels-sprouts"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2078),
                            ImageUrl = "carrots.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2078),
                            Name = "carrots"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2083),
                            ImageUrl = "cherries.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2083),
                            Name = "cherries"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2088),
                            ImageUrl = "chilis.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2088),
                            Name = "chilis"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2094),
                            ImageUrl = "coconuts.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2094),
                            Name = "coconuts"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2099),
                            ImageUrl = "coriander.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2099),
                            Name = "coriander"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2104),
                            ImageUrl = "corn.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2104),
                            Name = "corn"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2110),
                            ImageUrl = "cucumbers.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2110),
                            Name = "cucumbers"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2116),
                            ImageUrl = "dragon-fruits.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2116),
                            Name = "dragon-fruits"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2119),
                            ImageUrl = "durians.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2119),
                            Name = "durians"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2124),
                            ImageUrl = "eggplants.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2124),
                            Name = "eggplants"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2128),
                            ImageUrl = "garlic.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2128),
                            Name = "garlic"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2132),
                            ImageUrl = "grapes.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2132),
                            Name = "grapes"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2138),
                            ImageUrl = "guavas.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2138),
                            Name = "guavas"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2146),
                            ImageUrl = "kiwis.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2146),
                            Name = "kiwis"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2155),
                            ImageUrl = "lemons.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2155),
                            Name = "lemons"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2164),
                            ImageUrl = "mangos.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2164),
                            Name = "mangos"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2174),
                            ImageUrl = "mangosteens.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2174),
                            Name = "mangosteens"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2178),
                            ImageUrl = "melons.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2178),
                            Name = "melons"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2182),
                            ImageUrl = "mushrooms.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2182),
                            Name = "mushrooms"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2185),
                            ImageUrl = "olives.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2185),
                            Name = "olives"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2189),
                            ImageUrl = "oranges.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2189),
                            Name = "oranges"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2193),
                            ImageUrl = "papayas.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2193),
                            Name = "papayas"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2197),
                            ImageUrl = "peaches.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2197),
                            Name = "peaches"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2201),
                            ImageUrl = "pears.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2201),
                            Name = "pears"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2206),
                            ImageUrl = "peas.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2206),
                            Name = "peas"
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2210),
                            ImageUrl = "pineapples.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2210),
                            Name = "pineapples"
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2214),
                            ImageUrl = "pomegranates.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2214),
                            Name = "pomegranates"
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2218),
                            ImageUrl = "potatoes.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2218),
                            Name = "potatoes"
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2222),
                            ImageUrl = "pumpkins.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2222),
                            Name = "pumpkins"
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2230),
                            ImageUrl = "radish.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2230),
                            Name = "radish"
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2240),
                            ImageUrl = "radishes.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2240),
                            Name = "radishes"
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2249),
                            ImageUrl = "raspberries.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2249),
                            Name = "raspberries"
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2259),
                            ImageUrl = "salad.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2259),
                            Name = "salad"
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2269),
                            ImageUrl = "salads.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2269),
                            Name = "salads"
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2278),
                            ImageUrl = "scallions.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2278),
                            Name = "scallions"
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2307),
                            ImageUrl = "spinach.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2307),
                            Name = "spinach"
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2315),
                            ImageUrl = "star-fruits.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2315),
                            Name = "star-fruits"
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2319),
                            ImageUrl = "strawberries.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2319),
                            Name = "strawberries"
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2323),
                            ImageUrl = "sweet-potatoes.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2323),
                            Name = "sweet-potatoes"
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2333),
                            ImageUrl = "tomatoes.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2333),
                            Name = "tomatoes"
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2342),
                            ImageUrl = "watermelons.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2342),
                            Name = "watermelons"
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2346),
                            ImageUrl = "v-coin.svg",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 793, DateTimeKind.Local).AddTicks(2346),
                            Name = "v-coin"
                        });
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProposerId")
                        .HasColumnType("int");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProposerId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("Trades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Completed = false,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2611),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2611),
                            ProposerId = 0,
                            ReceiverId = 0
                        },
                        new
                        {
                            Id = 2,
                            Completed = false,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2684),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2684),
                            ProposerId = 0,
                            ReceiverId = 0
                        },
                        new
                        {
                            Id = 3,
                            Completed = false,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2699),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2699),
                            ProposerId = 0,
                            ReceiverId = 0
                        },
                        new
                        {
                            Id = 4,
                            Completed = false,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2704),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2704),
                            ProposerId = 0,
                            ReceiverId = 0
                        },
                        new
                        {
                            Id = 5,
                            Completed = false,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2708),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2708),
                            ProposerId = 0,
                            ReceiverId = 0
                        },
                        new
                        {
                            Id = 6,
                            Completed = false,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2713),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2713),
                            ProposerId = 0,
                            ReceiverId = 0
                        },
                        new
                        {
                            Id = 7,
                            Completed = false,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2723),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2723),
                            ProposerId = 0,
                            ReceiverId = 0
                        },
                        new
                        {
                            Id = 8,
                            Completed = false,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2731),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2731),
                            ProposerId = 0,
                            ReceiverId = 0
                        },
                        new
                        {
                            Id = 9,
                            Completed = false,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2735),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2735),
                            ProposerId = 0,
                            ReceiverId = 0
                        },
                        new
                        {
                            Id = 10,
                            Completed = false,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2739),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2739),
                            ProposerId = 0,
                            ReceiverId = 0
                        },
                        new
                        {
                            Id = 11,
                            Completed = false,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2743),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2743),
                            ProposerId = 0,
                            ReceiverId = 0
                        },
                        new
                        {
                            Id = 12,
                            Completed = false,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2748),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2748),
                            ProposerId = 0,
                            ReceiverId = 0
                        },
                        new
                        {
                            Id = 13,
                            Completed = false,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2752),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2752),
                            ProposerId = 0,
                            ReceiverId = 0
                        },
                        new
                        {
                            Id = 14,
                            Completed = false,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2756),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2756),
                            ProposerId = 0,
                            ReceiverId = 0
                        },
                        new
                        {
                            Id = 15,
                            Completed = false,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2765),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2765),
                            ProposerId = 0,
                            ReceiverId = 0
                        },
                        new
                        {
                            Id = 16,
                            Completed = false,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2775),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2775),
                            ProposerId = 0,
                            ReceiverId = 0
                        },
                        new
                        {
                            Id = 17,
                            Completed = false,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2783),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2783),
                            ProposerId = 0,
                            ReceiverId = 0
                        },
                        new
                        {
                            Id = 18,
                            Completed = false,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2793),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2793),
                            ProposerId = 0,
                            ReceiverId = 0
                        },
                        new
                        {
                            Id = 19,
                            Completed = false,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2801),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(2801),
                            ProposerId = 0,
                            ReceiverId = 0
                        });
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.TradeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<bool>("Sold")
                        .HasColumnType("bit");

                    b.Property<int?>("TradeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("TradeId");

                    b.HasIndex("UserId");

                    b.ToTable("TradeItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 2,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(7189),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 794, DateTimeKind.Local).AddTicks(7189),
                            ResourceId = 51,
                            Sold = false,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 781, DateTimeKind.Local).AddTicks(1310),
                            Email = "Pieter@mail.com",
                            FirstName = "Pieter",
                            ImageUrl = "https://robohash.org/Pieter",
                            IsAdmin = true,
                            LastName = "Corp",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 781, DateTimeKind.Local).AddTicks(1310),
                            PasswordHash = new byte[] { 243, 187, 162, 197, 19, 248, 231, 181, 246, 187, 188, 229, 192, 61, 129, 178, 56, 208, 19, 16, 227, 121, 104, 203, 174, 160, 254, 202, 254, 243, 2, 32, 243, 28, 185, 158, 108, 246, 106, 107, 47, 153, 14, 12, 173, 205, 27, 194, 93, 251, 169, 52, 168, 113, 181, 72, 160, 206, 69, 202, 124, 5, 108, 82 },
                            PasswordSalt = new byte[] { 53, 241, 191, 119, 238, 219, 26, 60, 85, 200, 127, 164, 69, 25, 219, 238, 47, 54, 72, 230, 178, 149, 0, 42, 7, 217, 173, 49, 8, 133, 140, 2, 98, 126, 28, 148, 95, 187, 96, 79, 158, 205, 60, 143, 153, 22, 69, 48, 134, 202, 206, 161, 30, 164, 122, 142, 52, 219, 133, 113, 60, 190, 162, 27, 171, 109, 143, 85, 235, 1, 25, 103, 101, 185, 72, 42, 182, 145, 163, 42, 241, 199, 111, 210, 191, 61, 160, 85, 105, 53, 104, 43, 199, 221, 93, 41, 193, 220, 112, 144, 183, 18, 142, 121, 220, 171, 143, 79, 69, 247, 134, 127, 116, 253, 221, 28, 64, 175, 241, 230, 109, 47, 80, 183, 90, 246, 79, 102 }
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 785, DateTimeKind.Local).AddTicks(5268),
                            Email = "Nick@mail.com",
                            FirstName = "Nick",
                            ImageUrl = "https://robohash.org/Nick",
                            IsAdmin = true,
                            LastName = "Vr",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 785, DateTimeKind.Local).AddTicks(5268),
                            PasswordHash = new byte[] { 243, 187, 162, 197, 19, 248, 231, 181, 246, 187, 188, 229, 192, 61, 129, 178, 56, 208, 19, 16, 227, 121, 104, 203, 174, 160, 254, 202, 254, 243, 2, 32, 243, 28, 185, 158, 108, 246, 106, 107, 47, 153, 14, 12, 173, 205, 27, 194, 93, 251, 169, 52, 168, 113, 181, 72, 160, 206, 69, 202, 124, 5, 108, 82 },
                            PasswordSalt = new byte[] { 53, 241, 191, 119, 238, 219, 26, 60, 85, 200, 127, 164, 69, 25, 219, 238, 47, 54, 72, 230, 178, 149, 0, 42, 7, 217, 173, 49, 8, 133, 140, 2, 98, 126, 28, 148, 95, 187, 96, 79, 158, 205, 60, 143, 153, 22, 69, 48, 134, 202, 206, 161, 30, 164, 122, 142, 52, 219, 133, 113, 60, 190, 162, 27, 171, 109, 143, 85, 235, 1, 25, 103, 101, 185, 72, 42, 182, 145, 163, 42, 241, 199, 111, 210, 191, 61, 160, 85, 105, 53, 104, 43, 199, 221, 93, 41, 193, 220, 112, 144, 183, 18, 142, 121, 220, 171, 143, 79, 69, 247, 134, 127, 116, 253, 221, 28, 64, 175, 241, 230, 109, 47, 80, 183, 90, 246, 79, 102 }
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 785, DateTimeKind.Local).AddTicks(5672),
                            Email = "Kobe@mail.com",
                            FirstName = "Kobe",
                            ImageUrl = "https://robohash.org/Kobe",
                            IsAdmin = true,
                            LastName = "Delo",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 785, DateTimeKind.Local).AddTicks(5672),
                            PasswordHash = new byte[] { 243, 187, 162, 197, 19, 248, 231, 181, 246, 187, 188, 229, 192, 61, 129, 178, 56, 208, 19, 16, 227, 121, 104, 203, 174, 160, 254, 202, 254, 243, 2, 32, 243, 28, 185, 158, 108, 246, 106, 107, 47, 153, 14, 12, 173, 205, 27, 194, 93, 251, 169, 52, 168, 113, 181, 72, 160, 206, 69, 202, 124, 5, 108, 82 },
                            PasswordSalt = new byte[] { 53, 241, 191, 119, 238, 219, 26, 60, 85, 200, 127, 164, 69, 25, 219, 238, 47, 54, 72, 230, 178, 149, 0, 42, 7, 217, 173, 49, 8, 133, 140, 2, 98, 126, 28, 148, 95, 187, 96, 79, 158, 205, 60, 143, 153, 22, 69, 48, 134, 202, 206, 161, 30, 164, 122, 142, 52, 219, 133, 113, 60, 190, 162, 27, 171, 109, 143, 85, 235, 1, 25, 103, 101, 185, 72, 42, 182, 145, 163, 42, 241, 199, 111, 210, 191, 61, 160, 85, 105, 53, 104, 43, 199, 221, 93, 41, 193, 220, 112, 144, 183, 18, 142, 121, 220, 171, 143, 79, 69, 247, 134, 127, 116, 253, 221, 28, 64, 175, 241, 230, 109, 47, 80, 183, 90, 246, 79, 102 }
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 785, DateTimeKind.Local).AddTicks(5709),
                            Email = "Dries@mail.com",
                            FirstName = "Dries",
                            ImageUrl = "https://robohash.org/Dries",
                            IsAdmin = true,
                            LastName = "Maes",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 785, DateTimeKind.Local).AddTicks(5709),
                            PasswordHash = new byte[] { 243, 187, 162, 197, 19, 248, 231, 181, 246, 187, 188, 229, 192, 61, 129, 178, 56, 208, 19, 16, 227, 121, 104, 203, 174, 160, 254, 202, 254, 243, 2, 32, 243, 28, 185, 158, 108, 246, 106, 107, 47, 153, 14, 12, 173, 205, 27, 194, 93, 251, 169, 52, 168, 113, 181, 72, 160, 206, 69, 202, 124, 5, 108, 82 },
                            PasswordSalt = new byte[] { 53, 241, 191, 119, 238, 219, 26, 60, 85, 200, 127, 164, 69, 25, 219, 238, 47, 54, 72, 230, 178, 149, 0, 42, 7, 217, 173, 49, 8, 133, 140, 2, 98, 126, 28, 148, 95, 187, 96, 79, 158, 205, 60, 143, 153, 22, 69, 48, 134, 202, 206, 161, 30, 164, 122, 142, 52, 219, 133, 113, 60, 190, 162, 27, 171, 109, 143, 85, 235, 1, 25, 103, 101, 185, 72, 42, 182, 145, 163, 42, 241, 199, 111, 210, 191, 61, 160, 85, 105, 53, 104, 43, 199, 221, 93, 41, 193, 220, 112, 144, 183, 18, 142, 121, 220, 171, 143, 79, 69, 247, 134, 127, 116, 253, 221, 28, 64, 175, 241, 230, 109, 47, 80, 183, 90, 246, 79, 102 }
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 785, DateTimeKind.Local).AddTicks(5730),
                            Email = "BartjeWevertje@mail.com",
                            FirstName = "BartjeWevertje",
                            ImageUrl = "https://robohash.org/BartjeWevertje",
                            IsAdmin = false,
                            LastName = "Wevertje",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 785, DateTimeKind.Local).AddTicks(5730),
                            PasswordHash = new byte[] { 243, 187, 162, 197, 19, 248, 231, 181, 246, 187, 188, 229, 192, 61, 129, 178, 56, 208, 19, 16, 227, 121, 104, 203, 174, 160, 254, 202, 254, 243, 2, 32, 243, 28, 185, 158, 108, 246, 106, 107, 47, 153, 14, 12, 173, 205, 27, 194, 93, 251, 169, 52, 168, 113, 181, 72, 160, 206, 69, 202, 124, 5, 108, 82 },
                            PasswordSalt = new byte[] { 53, 241, 191, 119, 238, 219, 26, 60, 85, 200, 127, 164, 69, 25, 219, 238, 47, 54, 72, 230, 178, 149, 0, 42, 7, 217, 173, 49, 8, 133, 140, 2, 98, 126, 28, 148, 95, 187, 96, 79, 158, 205, 60, 143, 153, 22, 69, 48, 134, 202, 206, 161, 30, 164, 122, 142, 52, 219, 133, 113, 60, 190, 162, 27, 171, 109, 143, 85, 235, 1, 25, 103, 101, 185, 72, 42, 182, 145, 163, 42, 241, 199, 111, 210, 191, 61, 160, 85, 105, 53, 104, 43, 199, 221, 93, 41, 193, 220, 112, 144, 183, 18, 142, 121, 220, 171, 143, 79, 69, 247, 134, 127, 116, 253, 221, 28, 64, 175, 241, 230, 109, 47, 80, 183, 90, 246, 79, 102 }
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 785, DateTimeKind.Local).AddTicks(5752),
                            Email = "Stofzuiger@mail.com",
                            FirstName = "Stofzuiger",
                            ImageUrl = "https://robohash.org/Stofzuiger",
                            IsAdmin = false,
                            LastName = "Zuiger",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 785, DateTimeKind.Local).AddTicks(5752),
                            PasswordHash = new byte[] { 243, 187, 162, 197, 19, 248, 231, 181, 246, 187, 188, 229, 192, 61, 129, 178, 56, 208, 19, 16, 227, 121, 104, 203, 174, 160, 254, 202, 254, 243, 2, 32, 243, 28, 185, 158, 108, 246, 106, 107, 47, 153, 14, 12, 173, 205, 27, 194, 93, 251, 169, 52, 168, 113, 181, 72, 160, 206, 69, 202, 124, 5, 108, 82 },
                            PasswordSalt = new byte[] { 53, 241, 191, 119, 238, 219, 26, 60, 85, 200, 127, 164, 69, 25, 219, 238, 47, 54, 72, 230, 178, 149, 0, 42, 7, 217, 173, 49, 8, 133, 140, 2, 98, 126, 28, 148, 95, 187, 96, 79, 158, 205, 60, 143, 153, 22, 69, 48, 134, 202, 206, 161, 30, 164, 122, 142, 52, 219, 133, 113, 60, 190, 162, 27, 171, 109, 143, 85, 235, 1, 25, 103, 101, 185, 72, 42, 182, 145, 163, 42, 241, 199, 111, 210, 191, 61, 160, 85, 105, 53, 104, 43, 199, 221, 93, 41, 193, 220, 112, 144, 183, 18, 142, 121, 220, 171, 143, 79, 69, 247, 134, 127, 116, 253, 221, 28, 64, 175, 241, 230, 109, 47, 80, 183, 90, 246, 79, 102 }
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 785, DateTimeKind.Local).AddTicks(5774),
                            Email = "Dirk@mail.com",
                            FirstName = "Dirk",
                            ImageUrl = "https://robohash.org/Dirk",
                            IsAdmin = false,
                            LastName = "Visser",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 785, DateTimeKind.Local).AddTicks(5774),
                            PasswordHash = new byte[] { 243, 187, 162, 197, 19, 248, 231, 181, 246, 187, 188, 229, 192, 61, 129, 178, 56, 208, 19, 16, 227, 121, 104, 203, 174, 160, 254, 202, 254, 243, 2, 32, 243, 28, 185, 158, 108, 246, 106, 107, 47, 153, 14, 12, 173, 205, 27, 194, 93, 251, 169, 52, 168, 113, 181, 72, 160, 206, 69, 202, 124, 5, 108, 82 },
                            PasswordSalt = new byte[] { 53, 241, 191, 119, 238, 219, 26, 60, 85, 200, 127, 164, 69, 25, 219, 238, 47, 54, 72, 230, 178, 149, 0, 42, 7, 217, 173, 49, 8, 133, 140, 2, 98, 126, 28, 148, 95, 187, 96, 79, 158, 205, 60, 143, 153, 22, 69, 48, 134, 202, 206, 161, 30, 164, 122, 142, 52, 219, 133, 113, 60, 190, 162, 27, 171, 109, 143, 85, 235, 1, 25, 103, 101, 185, 72, 42, 182, 145, 163, 42, 241, 199, 111, 210, 191, 61, 160, 85, 105, 53, 104, 43, 199, 221, 93, 41, 193, 220, 112, 144, 183, 18, 142, 121, 220, 171, 143, 79, 69, 247, 134, 127, 116, 253, 221, 28, 64, 175, 241, 230, 109, 47, 80, 183, 90, 246, 79, 102 }
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 785, DateTimeKind.Local).AddTicks(5795),
                            Email = "Andreas@mail.com",
                            FirstName = "Andreas",
                            ImageUrl = "https://robohash.org/Andreas",
                            IsAdmin = false,
                            LastName = "VanGrieken",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 785, DateTimeKind.Local).AddTicks(5795),
                            PasswordHash = new byte[] { 243, 187, 162, 197, 19, 248, 231, 181, 246, 187, 188, 229, 192, 61, 129, 178, 56, 208, 19, 16, 227, 121, 104, 203, 174, 160, 254, 202, 254, 243, 2, 32, 243, 28, 185, 158, 108, 246, 106, 107, 47, 153, 14, 12, 173, 205, 27, 194, 93, 251, 169, 52, 168, 113, 181, 72, 160, 206, 69, 202, 124, 5, 108, 82 },
                            PasswordSalt = new byte[] { 53, 241, 191, 119, 238, 219, 26, 60, 85, 200, 127, 164, 69, 25, 219, 238, 47, 54, 72, 230, 178, 149, 0, 42, 7, 217, 173, 49, 8, 133, 140, 2, 98, 126, 28, 148, 95, 187, 96, 79, 158, 205, 60, 143, 153, 22, 69, 48, 134, 202, 206, 161, 30, 164, 122, 142, 52, 219, 133, 113, 60, 190, 162, 27, 171, 109, 143, 85, 235, 1, 25, 103, 101, 185, 72, 42, 182, 145, 163, 42, 241, 199, 111, 210, 191, 61, 160, 85, 105, 53, 104, 43, 199, 221, 93, 41, 193, 220, 112, 144, 183, 18, 142, 121, 220, 171, 143, 79, 69, 247, 134, 127, 116, 253, 221, 28, 64, 175, 241, 230, 109, 47, 80, 183, 90, 246, 79, 102 }
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 785, DateTimeKind.Local).AddTicks(5817),
                            Email = "Mihiel@mail.com",
                            FirstName = "Mihiel",
                            ImageUrl = "https://robohash.org/Mihiel",
                            IsAdmin = false,
                            LastName = "Mihoen",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 785, DateTimeKind.Local).AddTicks(5817),
                            PasswordHash = new byte[] { 243, 187, 162, 197, 19, 248, 231, 181, 246, 187, 188, 229, 192, 61, 129, 178, 56, 208, 19, 16, 227, 121, 104, 203, 174, 160, 254, 202, 254, 243, 2, 32, 243, 28, 185, 158, 108, 246, 106, 107, 47, 153, 14, 12, 173, 205, 27, 194, 93, 251, 169, 52, 168, 113, 181, 72, 160, 206, 69, 202, 124, 5, 108, 82 },
                            PasswordSalt = new byte[] { 53, 241, 191, 119, 238, 219, 26, 60, 85, 200, 127, 164, 69, 25, 219, 238, 47, 54, 72, 230, 178, 149, 0, 42, 7, 217, 173, 49, 8, 133, 140, 2, 98, 126, 28, 148, 95, 187, 96, 79, 158, 205, 60, 143, 153, 22, 69, 48, 134, 202, 206, 161, 30, 164, 122, 142, 52, 219, 133, 113, 60, 190, 162, 27, 171, 109, 143, 85, 235, 1, 25, 103, 101, 185, 72, 42, 182, 145, 163, 42, 241, 199, 111, 210, 191, 61, 160, 85, 105, 53, 104, 43, 199, 221, 93, 41, 193, 220, 112, 144, 183, 18, 142, 121, 220, 171, 143, 79, 69, 247, 134, 127, 116, 253, 221, 28, 64, 175, 241, 230, 109, 47, 80, 183, 90, 246, 79, 102 }
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 785, DateTimeKind.Local).AddTicks(5838),
                            Email = "Luc@mail.com",
                            FirstName = "Luc",
                            ImageUrl = "https://robohash.org/Luc",
                            IsAdmin = false,
                            LastName = "DeHaantje",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 785, DateTimeKind.Local).AddTicks(5838),
                            PasswordHash = new byte[] { 243, 187, 162, 197, 19, 248, 231, 181, 246, 187, 188, 229, 192, 61, 129, 178, 56, 208, 19, 16, 227, 121, 104, 203, 174, 160, 254, 202, 254, 243, 2, 32, 243, 28, 185, 158, 108, 246, 106, 107, 47, 153, 14, 12, 173, 205, 27, 194, 93, 251, 169, 52, 168, 113, 181, 72, 160, 206, 69, 202, 124, 5, 108, 82 },
                            PasswordSalt = new byte[] { 53, 241, 191, 119, 238, 219, 26, 60, 85, 200, 127, 164, 69, 25, 219, 238, 47, 54, 72, 230, 178, 149, 0, 42, 7, 217, 173, 49, 8, 133, 140, 2, 98, 126, 28, 148, 95, 187, 96, 79, 158, 205, 60, 143, 153, 22, 69, 48, 134, 202, 206, 161, 30, 164, 122, 142, 52, 219, 133, 113, 60, 190, 162, 27, 171, 109, 143, 85, 235, 1, 25, 103, 101, 185, 72, 42, 182, 145, 163, 42, 241, 199, 111, 210, 191, 61, 160, 85, 105, 53, 104, 43, 199, 221, 93, 41, 193, 220, 112, 144, 183, 18, 142, 121, 220, 171, 143, 79, 69, 247, 134, 127, 116, 253, 221, 28, 64, 175, 241, 230, 109, 47, 80, 183, 90, 246, 79, 102 }
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 785, DateTimeKind.Local).AddTicks(5858),
                            Email = "VerhofstadDeZeemlap@europeesemailadres.com",
                            FirstName = "Verhofstad",
                            ImageUrl = "https://robohash.org/Zeemlap",
                            IsAdmin = false,
                            LastName = "Zeemlap",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 785, DateTimeKind.Local).AddTicks(5858),
                            PasswordHash = new byte[] { 243, 187, 162, 197, 19, 248, 231, 181, 246, 187, 188, 229, 192, 61, 129, 178, 56, 208, 19, 16, 227, 121, 104, 203, 174, 160, 254, 202, 254, 243, 2, 32, 243, 28, 185, 158, 108, 246, 106, 107, 47, 153, 14, 12, 173, 205, 27, 194, 93, 251, 169, 52, 168, 113, 181, 72, 160, 206, 69, 202, 124, 5, 108, 82 },
                            PasswordSalt = new byte[] { 53, 241, 191, 119, 238, 219, 26, 60, 85, 200, 127, 164, 69, 25, 219, 238, 47, 54, 72, 230, 178, 149, 0, 42, 7, 217, 173, 49, 8, 133, 140, 2, 98, 126, 28, 148, 95, 187, 96, 79, 158, 205, 60, 143, 153, 22, 69, 48, 134, 202, 206, 161, 30, 164, 122, 142, 52, 219, 133, 113, 60, 190, 162, 27, 171, 109, 143, 85, 235, 1, 25, 103, 101, 185, 72, 42, 182, 145, 163, 42, 241, 199, 111, 210, 191, 61, 160, 85, 105, 53, 104, 43, 199, 221, 93, 41, 193, 220, 112, 144, 183, 18, 142, 121, 220, 171, 143, 79, 69, 247, 134, 127, 116, 253, 221, 28, 64, 175, 241, 230, 109, 47, 80, 183, 90, 246, 79, 102 }
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 785, DateTimeKind.Local).AddTicks(5991),
                            Email = "Driesdentweedenmaarnidezelfden@mail.com",
                            FirstName = "Dries",
                            ImageUrl = "https://robohash.org/Dries2",
                            IsAdmin = false,
                            LastName = "VanKorteNekke",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 785, DateTimeKind.Local).AddTicks(5991),
                            PasswordHash = new byte[] { 243, 187, 162, 197, 19, 248, 231, 181, 246, 187, 188, 229, 192, 61, 129, 178, 56, 208, 19, 16, 227, 121, 104, 203, 174, 160, 254, 202, 254, 243, 2, 32, 243, 28, 185, 158, 108, 246, 106, 107, 47, 153, 14, 12, 173, 205, 27, 194, 93, 251, 169, 52, 168, 113, 181, 72, 160, 206, 69, 202, 124, 5, 108, 82 },
                            PasswordSalt = new byte[] { 53, 241, 191, 119, 238, 219, 26, 60, 85, 200, 127, 164, 69, 25, 219, 238, 47, 54, 72, 230, 178, 149, 0, 42, 7, 217, 173, 49, 8, 133, 140, 2, 98, 126, 28, 148, 95, 187, 96, 79, 158, 205, 60, 143, 153, 22, 69, 48, 134, 202, 206, 161, 30, 164, 122, 142, 52, 219, 133, 113, 60, 190, 162, 27, 171, 109, 143, 85, 235, 1, 25, 103, 101, 185, 72, 42, 182, 145, 163, 42, 241, 199, 111, 210, 191, 61, 160, 85, 105, 53, 104, 43, 199, 221, 93, 41, 193, 220, 112, 144, 183, 18, 142, 121, 220, 171, 143, 79, 69, 247, 134, 127, 116, 253, 221, 28, 64, 175, 241, 230, 109, 47, 80, 183, 90, 246, 79, 102 }
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 785, DateTimeKind.Local).AddTicks(6016),
                            Email = "Joyce@mail.com",
                            FirstName = "Joyce",
                            ImageUrl = "https://robohash.org/Tomatenplukker",
                            IsAdmin = false,
                            LastName = "Tomatenplukker",
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 785, DateTimeKind.Local).AddTicks(6016),
                            PasswordHash = new byte[] { 243, 187, 162, 197, 19, 248, 231, 181, 246, 187, 188, 229, 192, 61, 129, 178, 56, 208, 19, 16, 227, 121, 104, 203, 174, 160, 254, 202, 254, 243, 2, 32, 243, 28, 185, 158, 108, 246, 106, 107, 47, 153, 14, 12, 173, 205, 27, 194, 93, 251, 169, 52, 168, 113, 181, 72, 160, 206, 69, 202, 124, 5, 108, 82 },
                            PasswordSalt = new byte[] { 53, 241, 191, 119, 238, 219, 26, 60, 85, 200, 127, 164, 69, 25, 219, 238, 47, 54, 72, 230, 178, 149, 0, 42, 7, 217, 173, 49, 8, 133, 140, 2, 98, 126, 28, 148, 95, 187, 96, 79, 158, 205, 60, 143, 153, 22, 69, 48, 134, 202, 206, 161, 30, 164, 122, 142, 52, 219, 133, 113, 60, 190, 162, 27, 171, 109, 143, 85, 235, 1, 25, 103, 101, 185, 72, 42, 182, 145, 163, 42, 241, 199, 111, 210, 191, 61, 160, 85, 105, 53, 104, 43, 199, 221, 93, 41, 193, 220, 112, 144, 183, 18, 142, 121, 220, 171, 143, 79, 69, 247, 134, 127, 116, 253, 221, 28, 64, 175, 241, 230, 109, 47, 80, 183, 90, 246, 79, 102 }
                        });
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("VAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 790, DateTimeKind.Local).AddTicks(3684),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 790, DateTimeKind.Local).AddTicks(3684),
                            UserId = 1,
                            VAmount = 200m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 790, DateTimeKind.Local).AddTicks(5011),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 790, DateTimeKind.Local).AddTicks(5011),
                            UserId = 2,
                            VAmount = 347m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 790, DateTimeKind.Local).AddTicks(5029),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 790, DateTimeKind.Local).AddTicks(5029),
                            UserId = 3,
                            VAmount = 65m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 790, DateTimeKind.Local).AddTicks(5032),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 790, DateTimeKind.Local).AddTicks(5032),
                            UserId = 4,
                            VAmount = 42m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 790, DateTimeKind.Local).AddTicks(5036),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 790, DateTimeKind.Local).AddTicks(5036),
                            UserId = 5,
                            VAmount = 753m
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 790, DateTimeKind.Local).AddTicks(5039),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 790, DateTimeKind.Local).AddTicks(5039),
                            UserId = 6,
                            VAmount = 36m
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 790, DateTimeKind.Local).AddTicks(5042),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 790, DateTimeKind.Local).AddTicks(5042),
                            UserId = 7,
                            VAmount = 12m
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 790, DateTimeKind.Local).AddTicks(5045),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 790, DateTimeKind.Local).AddTicks(5045),
                            UserId = 8,
                            VAmount = 654m
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 790, DateTimeKind.Local).AddTicks(5048),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 790, DateTimeKind.Local).AddTicks(5048),
                            UserId = 9,
                            VAmount = 357m
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 790, DateTimeKind.Local).AddTicks(5051),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 790, DateTimeKind.Local).AddTicks(5051),
                            UserId = 10,
                            VAmount = 124m
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 790, DateTimeKind.Local).AddTicks(5055),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 790, DateTimeKind.Local).AddTicks(5055),
                            UserId = 11,
                            VAmount = 269m
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 790, DateTimeKind.Local).AddTicks(5057),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 790, DateTimeKind.Local).AddTicks(5057),
                            UserId = 12,
                            VAmount = 57m
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 5, 18, 17, 4, 53, 790, DateTimeKind.Local).AddTicks(5060),
                            ModifiedAt = new DateTime(2021, 5, 18, 17, 4, 53, 790, DateTimeKind.Local).AddTicks(5060),
                            UserId = 13,
                            VAmount = 204m
                        });
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Address", b =>
                {
                    b.HasOne("VeggieSwapServer.Data.Entities.User", "User")
                        .WithOne("Address")
                        .HasForeignKey("VeggieSwapServer.Data.Entities.Address", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Purchase", b =>
                {
                    b.HasOne("VeggieSwapServer.Data.Entities.Wallet", "Wallet")
                        .WithMany("Purchases")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Trade", b =>
                {
                    b.HasOne("VeggieSwapServer.Data.Entities.User", "Proposer")
                        .WithMany()
                        .HasForeignKey("ProposerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeggieSwapServer.Data.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proposer");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.TradeItem", b =>
                {
                    b.HasOne("VeggieSwapServer.Data.Entities.Resource", "Resource")
                        .WithMany("TradeItems")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeggieSwapServer.Data.Entities.Trade", null)
                        .WithMany("TradeItems")
                        .HasForeignKey("TradeId");

                    b.HasOne("VeggieSwapServer.Data.Entities.User", "User")
                        .WithMany("TradeItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Wallet", b =>
                {
                    b.HasOne("VeggieSwapServer.Data.Entities.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("VeggieSwapServer.Data.Entities.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Resource", b =>
                {
                    b.Navigation("TradeItems");
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Trade", b =>
                {
                    b.Navigation("TradeItems");
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.User", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("TradeItems");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("VeggieSwapServer.Data.Entities.Wallet", b =>
                {
                    b.Navigation("Purchases");
                });
#pragma warning restore 612, 618
        }
    }
}
